In [2]:
#loading data

import pandas as pd

old_model = pd.read_csv("results/old_model.csv")

In [3]:
new_model = pd.read_csv("results/new_model.csv")

In [4]:
newest_model = pd.read_csv("results/newest_model.csv")

In [5]:
model_4 = pd.read_csv("results/model_4.csv")

In [6]:
model_5 = pd.read_csv("results/model_5.csv")

In [7]:
model_6 = pd.read_csv("results/model_6.csv")

In [8]:
pathogenic_old_model = old_model[old_model['Predicted_Label_Display'] == 'Pathogenic']
pathogenic_old_model.head(50)

,snp_id,protein_sequence,variant_type,position,gene,original,mutant,frequency,function_class,Predicted_Label_Original,Prediction_Confidence,Predicted_Label_Display,normal_seq
2651,1024192776,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169479556,SLC19A2,G,A,A:0.000013:2:GnomAD_genomes|A:0.000026:7:TOPME...,intron_variant,-2,0.601129,Pathogenic,True
3063,1162160250,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169470034,SLC19A2,-,CA,CA:0.000002:1:GnomAD_exomes,frameshift_variant;coding_sequence_variant,-2,0.996361,Pathogenic,False
3519,1213206212,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468665,SLC19A2,AT,-,-:0.0000029:4:GnomAD_exomes,frameshift_variant;coding_sequence_variant,-2,0.999449,Pathogenic,False
3716,1234408990,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169478848,SLC19A2,G,A,A:0.000008:2:TOPMED|A:0.000071:1:ALFA,intron_variant,-2,0.628886,Pathogenic,True
3872,1251759726,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169479549,SLC19A2,A,T,T:0.000011:3:TOPMED|T:0.:0:ALFA,intron_variant,-2,0.666625,Pathogenic,True
4487,1323163365,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477297,SLC19A2,G,A,A:0.000007:1:GnomAD_genomes|A:0.:0:ALFA,intron_variant;coding_sequence_variant;missens...,-2,0.385200,Pathogenic,False
4758,1352602232,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486407,SLC19A2,G,A,A:0.000008:2:TOPMED|A:0.:0:ALFA,upstream_transcript_variant;2KB_upstream_variant,-2,0.492172,Pathogenic,True
4912,1372261451,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486642,SLC19A2,C,G,G:0.000008:2:TOPMED|G:0.:0:ALFA,upstream_transcript_variant;2KB_upstream_variant,-2,0.788101,Pathogenic,True
4960,1379204044,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468243,SLC19A2,A,-,NaN,frameshift_variant;coding_sequence_variant,-2,0.999944,Pathogenic,False
4988,1381515416,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474290,SLC19A2,T,G,G:0.000013:2:GnomAD_genomes|G:0.000004:1:TOPME...,intron_variant,-2,0.574073,Pathogenic,True
5165,1401618504,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480584,SLC19A2,A,C,C:0.:0:ALFA,intron_variant,-2,0.453556,Pathogenic,True
5177,1403986234,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486616,SLC19A2,T,C,C:0.000004:1:TOPMED|C:0.:0:ALFA,upstream_transcript_variant;2KB_upstream_variant,-2,0.608817,Pathogenic,True
5416,1424601135,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486653,SLC19A2,C,G,G:0.000004:1:TOPMED|G:0.:0:ALFA,upstream_transcript_variant;2KB_upstream_variant,-2,0.774957,Pathogenic,True
5478,1430758218,MCPARCLGGRRRRRPLCSCGPLGSVANAGSCRPRCSAPTASSPASG...,delins,169485816,SLC19A2,CCGCC,CC,-:0.:0:GnomAD_exomes|CC:0.0001132:1:ALFA,5_prime_UTR_variant,-2,0.990728,Pathogenic,False
5481,1430840234,MDVPGPVSRRAAAAAATVLLRTARVRREC,snv,169485678,SLC19A2,C,T,T:0.0000015:2:GnomAD_exomes|A:0.0000067:1:Gnom...,missense_variant;coding_sequence_variant;stop_...,-2,0.360311,Pathogenic,False
5950,1483075165,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474452,SLC19A2,T,C,C:0.000007:1:GnomAD_genomes|C:0.:0:ALFA,intron_variant,-2,0.789899,Pathogenic,True
6076,1553212202,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169471698,SLC19A2,-,GTGTATAT,TGTATAT:0.:0:ALFA,intron_variant,-2,0.432358,Pathogenic,True
6081,1553212202,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169471698,SLC19A2,-,GTGTGTAT,TGTATAT:0.:0:ALFA,intron_variant,-2,0.433294,Pathogenic,True
6106,1553213506,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFPAS...,del,169485637,SLC19A2,C,-,-:0.03163:329:GoESP,frameshift_variant;coding_sequence_variant,-2,0.999895,Pathogenic,False
6107,1553213508,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFSPAS...,del,169485641,SLC19A2,G,-,-:0.0238:256:GoESP,frameshift_variant;coding_sequence_variant,-2,0.921249,Pathogenic,False
6135,1557889112,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169469971,SLC19A2,G,-,-:0.000003:2:GnomAD_exomes|-:0.000004:1:TOPMED...,frameshift_variant;coding_sequence_variant,-2,0.998752,Pathogenic,False
6217,1557895498,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486549,SLC19A2,A,G,NaN,2KB_upstream_variant;upstream_transcript_variant,-2,0.511138,Pathogenic,True
6481,1571543939,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486775,SLC19A2,A,G,G:0.0003:1:KOREAN,2KB_upstream_variant;upstream_transcript_variant,-2,0.496571,Pathogenic,True
7026,1658076788,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468143,SLC19A2,C,-,-:0.000004:1:TOPMED|-:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.999898,Pathogenic,False
7027,1658076868,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468145,SLC19A2,-,TGTGTAG,TGTGTAG:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.964525,Pathogenic,False
7086,1658095371,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468752,SLC19A2,A,-,-:0.000008:2:TOPMED|-:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.999853,Pathogenic,False
7090,1658096725,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468795,SLC19A2,A,-,-:0.0000014:2:GnomAD_exomes|-:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.999288,Pathogenic,False
7094,1658097604,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468813,SLC19A2,-,A,AAA:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.999009,Pathogenic,False
7220,1658132918,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470100,SLC19A2,C,T,T:0.:0:ALFA,coding_sequence_variant;stop_gained,-2,0.987388,Pathogenic,False
7221,1658133007,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470101,SLC19A2,C,T,A:0.000002:1:GnomAD_exomes|T:0.:0:ALFA,coding_sequence_variant;stop_gained;missense_v...,-2,0.981043,Pathogenic,False
7716,1658259745,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474296,SLC19A2,T,A,A:0.:0:ALFA,intron_variant,-2,0.663617,Pathogenic,True
7718,1658259901,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169474303,SLC19A2,A,-,-:0.000004:1:TOPMED|AAA:0.:0:ALFA,intron_variant,-2,0.492398,Pathogenic,True
7725,1658260789,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474342,SLC19A2,T,C,C:0.00003:2:TOMMO,intron_variant,-2,0.475454,Pathogenic,True
7739,1658264691,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474439,SLC19A2,A,C,C:0.000007:1:GnomAD_genomes|C:0.000004:1:TOPME...,intron_variant,-2,0.863236,Pathogenic,True
7740,1658264737,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169474441,SLC19A2,TACATA,TA,-:0.000004:1:TOPMED|TA:0.:0:ALFA,intron_variant,-2,0.653388,Pathogenic,True
7742,1658264969,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474449,SLC19A2,G,C,T:0.000007:1:GnomAD_genomes|C:0.000004:1:TOPME...,intron_variant,-2,0.754386,Pathogenic,True
7743,1658264969,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474449,SLC19A2,G,T,T:0.000007:1:GnomAD_genomes|C:0.000004:1:TOPME...,intron_variant,-2,0.749964,Pathogenic,True
7920,1658296793,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169476029,SLC19A2,T,C,C:0.00017:13:TOMMO,intron_variant,-2,0.391478,Pathogenic,True
8100,1658355778,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477646,SLC19A2,-,C,C:0.000004:1:TOPMED|CCCCC:0.:0:ALFA,coding_sequence_variant;intron_variant;framesh...,-2,0.999193,Pathogenic,False
8260,1658385500,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169478844,SLC19A2,T,C,C:0.00001:1:TOMMO,intron_variant,-2,0.503705,Pathogenic,True
8262,1658385619,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169478854,SLC19A2,G,A,A:0.000004:1:TOPMED|A:0.:0:ALFA,intron_variant,-2,0.949310,Pathogenic,True
8974,1658538909,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169485565,SLC19A2,C,-,-:0.000007:1:GnomAD_genomes|-:0.000004:1:TOPME...,coding_sequence_variant;frameshift_variant,-2,0.994784,Pathogenic,False
8994,1658549091,MCPARCLGGRRRRRPLCSCGPLGSVANAGSCRPRCSAPTASSPASG...,delins,169485776,SLC19A2,GAGGG,G,G:0.:0:ALFA,5_prime_UTR_variant,-2,0.993104,Pathogenic,False
8999,1658551218,MCPARCLGGRRRRRPLCSCGPLGSVANAGSCRPRCSAPTASSPASG...,delins,169485788,SLC19A2,CCCGGCCC,CC,-:0.000007:1:GnomAD_genomes|CC:0.:0:ALFA,5_prime_UTR_variant,-2,0.946379,Pathogenic,False
9000,1658551595,MCPARCLGGRRRRRPLCSCGPLGSVANAGSCRPRCSAPTASSPASG...,delins,169485789,SLC19A2,CCGGCC,CC,CC:0.:0:ALFA,5_prime_UTR_variant,-2,0.904684,Pathogenic,False
9139,1658581493,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486606,SLC19A2,A,G,G:0.000004:1:TOPMED|G:0.:0:ALFA,upstream_transcript_variant;2KB_upstream_variant,-2,0.381368,Pathogenic,True
9140,1658581724,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486621,SLC19A2,G,C,C:0.000007:1:GnomAD_genomes|C:0.000008:2:TOPME...,upstream_transcript_variant;2KB_upstream_variant,-2,0.560957,Pathogenic,True
9142,1658582623,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486652,SLC19A2,A,C,C:0.000007:1:GnomAD_genomes|C:0.:0:ALFA,upstream_transcript_variant;2KB_upstream_variant,-2,0.782963,Pathogenic,True
9145,1658582941,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169486663,SLC19A2,GTTTATAGTT,GTT,-:0.000008:2:TOPMED|GTT:0.000094:1:ALFA,upstream_transcript_variant;2KB_upstream_variant,-2,0.668177,Pathogenic,True
9146,1658583161,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486680,SLC19A2,A,G,G:0.000004:1:TOPMED|G:0.:0:ALFA,upstream_transcript_variant;2KB_upstream_variant,-2,0.453361,Pathogenic,True

In [9]:
pathogenic_old_model.iloc[50:100]

,snp_id,protein_sequence,variant_type,position,gene,original,mutant,frequency,function_class,Predicted_Label_Original,Prediction_Confidence,Predicted_Label_Display,normal_seq
9149,1658583425,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486691,SLC19A2,C,A,A:0.000007:1:GnomAD_genomes|A:0.:0:ALFA,upstream_transcript_variant;2KB_upstream_variant,-2,0.625408,Pathogenic,True
9156,1658584605,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486761,SLC19A2,T,G,G:0.:0:ALFA,upstream_transcript_variant;2KB_upstream_variant,-2,0.666226,Pathogenic,True
9158,1658584791,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486779,SLC19A2,C,T,T:0.:0:ALFA,upstream_transcript_variant;2KB_upstream_variant,-2,0.744228,Pathogenic,True
9333,184529626,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474445,SLC19A2,T,G,C:0.00016:1:1000Genomes_30X|T:0.4:4:SGDP_PRJ|C...,intron_variant,-2,0.447955,Pathogenic,True
9354,186203570,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486682,SLC19A2,G,T,A:0.0002:1:1000Genomes|A:0.000156:1:1000Genome...,2KB_upstream_variant;upstream_transcript_variant,-2,0.681564,Pathogenic,True
9495,2101773099,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468113,SLC19A2,G,A,T:0.000002:1:GnomAD_exomes,missense_variant;stop_gained;coding_sequence_v...,-2,0.997194,Pathogenic,False
9497,2101773237,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468224,SLC19A2,C,A,A:0.00001:1:TOMMO,stop_gained;coding_sequence_variant,-2,0.999594,Pathogenic,False
9568,2101778811,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474351,SLC19A2,G,C,C:0.00001:1:TOMMO,intron_variant,-2,0.514698,Pathogenic,True
9618,2101782473,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169478939,SLC19A2,A,T,T:0.000156:1:1000Genomes_30X|T:0.000007:1:Gnom...,intron_variant,-2,0.505789,Pathogenic,True
9853,2526228997,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169465907,SLC19A2,-,T,T:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.808639,Pathogenic,False
9869,2526229323,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169466011,SLC19A2,A,G,G:0.0000021:3:GnomAD_exomes,intron_variant,-2,0.332860,Pathogenic,True
9966,2526234346,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468152,SLC19A2,CAATTAGAGTGAGCA,CA,-:0.0000043:6:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.975035,Pathogenic,False
10053,2526235999,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468658,SLC19A2,-,A,A:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.996009,Pathogenic,False
10061,2526236130,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468700,SLC19A2,G,-,-:0.00001:1:TOMMO,coding_sequence_variant;frameshift_variant,-2,0.999329,Pathogenic,False
10064,2526236154,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468706,SLC19A2,C,T,T:0.000002:1:GnomAD_exomes,coding_sequence_variant;stop_gained,-2,0.999566,Pathogenic,False
10072,2526236236,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468728,SLC19A2,-,C,C:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.918320,Pathogenic,False
10074,2526236253,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468730,SLC19A2,-,TGCAGCA,TGCAGCA:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.997474,Pathogenic,False
10075,2526236267,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468732,SLC19A2,-,CAGGAGAG,CAGGAGAG:0.0000007:1:GnomAD_exomes,inframe_indel;coding_sequence_variant;stop_gained,-2,0.999753,Pathogenic,False
10079,2526236348,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468759,SLC19A2,A,-,-:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.999099,Pathogenic,False
10083,2526236371,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468770,SLC19A2,A,-,-:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.999796,Pathogenic,False
10084,2526236447,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468791,SLC19A2,G,T,T:0.000002:1:GnomAD_exomes,coding_sequence_variant;stop_gained,-2,0.999677,Pathogenic,False
10085,2526236453,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468791,SLC19A2,GACCAG,G,-:0.000002:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.991713,Pathogenic,False
10087,2526236505,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468797,SLC19A2,-,TT,TT:0.000002:1:GnomAD_exomes,coding_sequence_variant;stop_gained,-2,0.951172,Pathogenic,False
10223,2526240071,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169470079,SLC19A2,AG,-,-:0.000002:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.999380,Pathogenic,False
10224,2526240078,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169470083,SLC19A2,A,-,-:0.000001:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.997338,Pathogenic,False
10401,2526255842,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477167,SLC19A2,G,-,-:0.0000014:2:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.946501,Pathogenic,False
10424,2526256167,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169477297,SLC19A2,-,T,T:0.000002:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.947796,Pathogenic,False
10428,2526256643,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477335,SLC19A2,AGGTAAAAACCAGG,AGG,-:0.0000007:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.999906,Pathogenic,False
10439,2526256896,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477403,SLC19A2,GCGACCAGCCTGCCACTG,G,-:0.0000014:2:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.999277,Pathogenic,False
10440,2526256902,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169477403,SLC19A2,-,A,A:0.0000007:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.999260,Pathogenic,False
10441,2526256925,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169477406,SLC19A2,-,T,T:0.000001:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.998965,Pathogenic,False
10442,2526256938,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477408,SLC19A2,C,T,T:0.000001:1:GnomAD_exomes,intron_variant;coding_sequence_variant;stop_ga...,-2,0.999426,Pathogenic,False
10448,2526257051,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477445,SLC19A2,A,T,T:0.000002:2:GnomAD_exomes,missense_variant;intron_variant;coding_sequenc...,-2,0.772864,Pathogenic,False
10458,2526257190,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169477503,SLC19A2,-,T,T:0.0000007:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.999213,Pathogenic,False
10459,2526257209,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169477505,SLC19A2,TGCC,-,-:0.0000007:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.999998,Pathogenic,False
10486,2526257854,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477696,SLC19A2,A,-,-:0.000001:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.999920,Pathogenic,False
10721,2526274073,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169485599,SLC19A2,-,T,T:0.0000007:1:GnomAD_exomes,coding_sequence_variant;stop_gained,-2,0.938775,Pathogenic,False
10746,2526275035,MDVPGPVSRRAAAAAPLCSCGPLGSVANAGSCRPRCSAPTASSPAS...,delins,169485721,SLC19A2,C,-,-:0.0000008:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.999996,Pathogenic,False
10755,2526275248,MCPARCLGGRRRRRPLCSCGPLGSVANAGSCRPRCSAPTASSPASG...,snv,169485766,SLC19A2,T,C,C:0.000001:1:GnomAD_exomes,missense_variant;initiator_codon_variant,-2,0.927169,Pathogenic,False
10771,2526275649,MCPARCLGGRRRRRPLCSCGPLGSVANAGSCRPRCSAPTASSPASG...,delins,169485808,SLC19A2,CTCCTCCTCC,CTCCTCC,-:0.0000023:3:GnomAD_exomes,5_prime_UTR_variant,-2,0.973480,Pathogenic,False
10791,2526276587,MCPARCLGGRRRRRPLCSCGPLGSVANAGSCRPRCSAPTASSPASG...,delins,169485878,SLC19A2,CAGGACGTTC,C,-:0.0000009:1:GnomAD_exomes,5_prime_UTR_variant,-2,0.997641,Pathogenic,False
10802,2526276701,MCPARCLGGRRRRRPLCSCGPLGSVANAGSCRPRCSAPTASSPASG...,delins,169485902,SLC19A2,CCTCC,C,-:0.000003:3:GnomAD_exomes,5_prime_UTR_variant,-2,0.924430,Pathogenic,False
10862,2526278693,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169486483,SLC19A2,G,A,A:0.00001:1:TOMMO,2KB_upstream_variant;upstream_transcript_variant,-2,0.420958,Pathogenic,True
10889,34688678,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169473410,SLC19A2,TTTT,TTTTTTTTTTTT,-:0.4325:2166:1000Genomes|-:0.475:19:GENOME_DK...,intron_variant,-2,0.617425,Pathogenic,True
10942,35735941,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477744,SLC19A2,-,T,NaN,frameshift_variant;intron_variant;coding_seque...,-2,0.964579,Pathogenic,False
10998,375833910,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477105,SLC19A2,G,A,A:0.000008:1:ExAC|A:0.000007:1:GnomAD_genomes|...,intron_variant,-2,0.969687,Pathogenic,True
11572,750554176,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477356,SLC19A2,A,-,-:0.000008:1:ExAC,coding_sequence_variant;intron_variant;framesh...,-2,0.999072,Pathogenic,False
11611,754086436,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169465954,SLC19A2,A,-,-:0.000008:1:ExAC|-:0.000002:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.993005,Pathogenic,False
11719,762044278,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477211,SLC19A2,C,-,-:0.000008:1:ExAC|-:0.000002:1:GnomAD_exomes,frameshift_variant;coding_sequence_variant;int...,-2,0.682325,Pathogenic,False
11800,767845548,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477405,SLC19A2,G,T,A:0.000066:8:ExAC|A:0.0000435:61:GnomAD_exomes...,stop_gained;intron_variant;coding_sequence_var...,-2,0.999106,Pathogenic,False

In [10]:
pathogenic_new_model = new_model[new_model['Predicted_Label_Display'] == 'Pathogenic']
pathogenic_new_model.head(50)

,snp_id,protein_sequence,variant_type,position,gene,original,mutant,frequency,function_class,Predicted_Label_Original,Prediction_Confidence,Predicted_Label_Display,normal_seq
3063,1162160250,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169470034,SLC19A2,-,CA,CA:0.000002:1:GnomAD_exomes,frameshift_variant;coding_sequence_variant,-2,0.976663,Pathogenic,False
3519,1213206212,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468665,SLC19A2,AT,-,-:0.0000029:4:GnomAD_exomes,frameshift_variant;coding_sequence_variant,-2,0.993755,Pathogenic,False
4960,1379204044,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468243,SLC19A2,A,-,NaN,frameshift_variant;coding_sequence_variant,-2,0.979383,Pathogenic,False
6106,1553213506,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFPAS...,del,169485637,SLC19A2,C,-,-:0.03163:329:GoESP,frameshift_variant;coding_sequence_variant,-2,0.933878,Pathogenic,False
6107,1553213508,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFSPAS...,del,169485641,SLC19A2,G,-,-:0.0238:256:GoESP,frameshift_variant;coding_sequence_variant,-2,0.624004,Pathogenic,False
6135,1557889112,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169469971,SLC19A2,G,-,-:0.000003:2:GnomAD_exomes|-:0.000004:1:TOPMED...,frameshift_variant;coding_sequence_variant,-2,0.993021,Pathogenic,False
7026,1658076788,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468143,SLC19A2,C,-,-:0.000004:1:TOPMED|-:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.905076,Pathogenic,False
7027,1658076868,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468145,SLC19A2,-,TGTGTAG,TGTGTAG:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.832900,Pathogenic,False
7086,1658095371,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468752,SLC19A2,A,-,-:0.000008:2:TOPMED|-:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.992494,Pathogenic,False
7090,1658096725,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468795,SLC19A2,A,-,-:0.0000014:2:GnomAD_exomes|-:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.990154,Pathogenic,False
7094,1658097604,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468813,SLC19A2,-,A,AAA:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.980829,Pathogenic,False
7220,1658132918,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470100,SLC19A2,C,T,T:0.:0:ALFA,coding_sequence_variant;stop_gained,-2,0.935515,Pathogenic,False
7221,1658133007,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470101,SLC19A2,C,T,A:0.000002:1:GnomAD_exomes|T:0.:0:ALFA,coding_sequence_variant;stop_gained;missense_v...,-2,0.926143,Pathogenic,False
8067,1658340278,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477202,SLC19A2,C,A,G:0.0000007:1:GnomAD_exomes|A:0.0000067:1:Gnom...,coding_sequence_variant;intron_variant;missens...,-2,0.751972,Pathogenic,False
8100,1658355778,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477646,SLC19A2,-,C,C:0.000004:1:TOPMED|CCCCC:0.:0:ALFA,coding_sequence_variant;intron_variant;framesh...,-2,0.998957,Pathogenic,False
8974,1658538909,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169485565,SLC19A2,C,-,-:0.000007:1:GnomAD_genomes|-:0.000004:1:TOPME...,coding_sequence_variant;frameshift_variant,-2,0.996943,Pathogenic,False
8994,1658549091,MCPARCLGGRRRRRPLCSCGPLGSVANAGSCRPRCSAPTASSPASG...,delins,169485776,SLC19A2,GAGGG,G,G:0.:0:ALFA,5_prime_UTR_variant,-2,0.995902,Pathogenic,False
9000,1658551595,MCPARCLGGRRRRRPLCSCGPLGSVANAGSCRPRCSAPTASSPASG...,delins,169485789,SLC19A2,CCGGCC,CC,CC:0.:0:ALFA,5_prime_UTR_variant,-2,0.990901,Pathogenic,False
9495,2101773099,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468113,SLC19A2,G,A,T:0.000002:1:GnomAD_exomes,missense_variant;stop_gained;coding_sequence_v...,-2,0.721731,Pathogenic,False
9497,2101773237,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468224,SLC19A2,C,A,A:0.00001:1:TOMMO,stop_gained;coding_sequence_variant,-2,0.951951,Pathogenic,False
9966,2526234346,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468152,SLC19A2,CAATTAGAGTGAGCA,CA,-:0.0000043:6:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.801196,Pathogenic,False
10053,2526235999,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468658,SLC19A2,-,A,A:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.983918,Pathogenic,False
10061,2526236130,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468700,SLC19A2,G,-,-:0.00001:1:TOMMO,coding_sequence_variant;frameshift_variant,-2,0.986545,Pathogenic,False
10064,2526236154,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468706,SLC19A2,C,T,T:0.000002:1:GnomAD_exomes,coding_sequence_variant;stop_gained,-2,0.983485,Pathogenic,False
10072,2526236236,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468728,SLC19A2,-,C,C:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.968812,Pathogenic,False
10074,2526236253,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468730,SLC19A2,-,TGCAGCA,TGCAGCA:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.980943,Pathogenic,False
10075,2526236267,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468732,SLC19A2,-,CAGGAGAG,CAGGAGAG:0.0000007:1:GnomAD_exomes,inframe_indel;coding_sequence_variant;stop_gained,-2,0.988322,Pathogenic,False
10079,2526236348,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468759,SLC19A2,A,-,-:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.988807,Pathogenic,False
10083,2526236371,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468770,SLC19A2,A,-,-:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.991464,Pathogenic,False
10084,2526236447,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468791,SLC19A2,G,T,T:0.000002:1:GnomAD_exomes,coding_sequence_variant;stop_gained,-2,0.985683,Pathogenic,False
10085,2526236453,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468791,SLC19A2,GACCAG,G,-:0.000002:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.985439,Pathogenic,False
10087,2526236505,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468797,SLC19A2,-,TT,TT:0.000002:1:GnomAD_exomes,coding_sequence_variant;stop_gained,-2,0.979277,Pathogenic,False
10223,2526240071,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169470079,SLC19A2,AG,-,-:0.000002:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.988503,Pathogenic,False
10224,2526240078,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169470083,SLC19A2,A,-,-:0.000001:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.970447,Pathogenic,False
10401,2526255842,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477167,SLC19A2,G,-,-:0.0000014:2:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.889270,Pathogenic,False
10424,2526256167,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169477297,SLC19A2,-,T,T:0.000002:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.943583,Pathogenic,False
10428,2526256643,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477335,SLC19A2,AGGTAAAAACCAGG,AGG,-:0.0000007:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.995350,Pathogenic,False
10439,2526256896,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477403,SLC19A2,GCGACCAGCCTGCCACTG,G,-:0.0000014:2:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.995406,Pathogenic,False
10440,2526256902,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169477403,SLC19A2,-,A,A:0.0000007:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.995379,Pathogenic,False
10441,2526256925,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169477406,SLC19A2,-,T,T:0.000001:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.995401,Pathogenic,False
10442,2526256938,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477408,SLC19A2,C,T,T:0.000001:1:GnomAD_exomes,intron_variant;coding_sequence_variant;stop_ga...,-2,0.993996,Pathogenic,False
10458,2526257190,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169477503,SLC19A2,-,T,T:0.0000007:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.999622,Pathogenic,False
10459,2526257209,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169477505,SLC19A2,TGCC,-,-:0.0000007:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.997985,Pathogenic,False
10486,2526257854,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477696,SLC19A2,A,-,-:0.000001:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.998699,Pathogenic,False
10746,2526275035,MDVPGPVSRRAAAAAPLCSCGPLGSVANAGSCRPRCSAPTASSPAS...,delins,169485721,SLC19A2,C,-,-:0.0000008:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.999002,Pathogenic,False
10755,2526275248,MDLLLPGATVSCVPCHRLPPL,snv,169485766,SLC19A2,T,C,C:0.000001:1:GnomAD_exomes,missense_variant;initiator_codon_variant,-2,0.970379,Pathogenic,False
10802,2526276701,MCPARCLGGRRRRRPLCSCGPLGSVANAGSCRPRCSAPTASSPASG...,delins,169485902,SLC19A2,CCTCC,C,-:0.000003:3:GnomAD_exomes,5_prime_UTR_variant,-2,0.995688,Pathogenic,False
10942,35735941,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477744,SLC19A2,-,T,NaN,frameshift_variant;intron_variant;coding_seque...,-2,0.960864,Pathogenic,False
11572,750554176,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477356,SLC19A2,A,-,-:0.000008:1:ExAC,coding_sequence_variant;intron_variant;framesh...,-2,0.987349,Pathogenic,False
11611,754086436,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169465954,SLC19A2,A,-,-:0.000008:1:ExAC|-:0.000002:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.468565,Pathogenic,False

In [11]:
pathogenic_new_model.iloc[50:100]

,snp_id,protein_sequence,variant_type,position,gene,original,mutant,frequency,function_class,Predicted_Label_Original,Prediction_Confidence,Predicted_Label_Display,normal_seq
11719,762044278,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477211,SLC19A2,C,-,-:0.000008:1:ExAC|-:0.000002:1:GnomAD_exomes,frameshift_variant;coding_sequence_variant;int...,-2,0.805362,Pathogenic,False
11785,767214420,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477680,SLC19A2,G,T,A:0.000008:1:ExAC|A:0.000005:3:GnomAD_exomes|A...,stop_gained;intron_variant;coding_sequence_var...,-2,0.934823,Pathogenic,False
11800,767845548,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477405,SLC19A2,G,T,A:0.000066:8:ExAC|A:0.0000435:61:GnomAD_exomes...,stop_gained;intron_variant;coding_sequence_var...,-2,0.994146,Pathogenic,False
11803,768372071,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169470028,SLC19A2,T,TT,-:0.000008:1:ExAC,coding_sequence_variant;frameshift_variant,-2,0.987613,Pathogenic,False
11804,768372071,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169470028,SLC19A2,T,-,-:0.000008:1:ExAC,coding_sequence_variant;frameshift_variant,-2,0.983734,Pathogenic,False
11849,772048171,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468699,SLC19A2,A,-,-:0.0000247:3:ExAC|-:0.:0:GnomAD_exomes,frameshift_variant;coding_sequence_variant,-2,0.989476,Pathogenic,False
13159,1003535408,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227708552,SLC19A3,T,C,C:0.000263:35:GnomAD_genomes|T:0.5:1:SGDP_PRJ|...,intron_variant;upstream_transcript_variant;gen...,-2,0.481890,Pathogenic,True
14177,1159149462,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,delins,227703204,SLC19A3,GGTTACATATATAG,G,-:0.000004:1:TOPMED|G:0.:0:ALFA,intron_variant,-2,0.538361,Pathogenic,True
14733,1192971909,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,delins,227699525,SLC19A3,-,AGGAGTATGT,GTAGGAGTAT:0.000004:1:TOPMED|GTAGGAGTATGTAGGAG...,coding_sequence_variant;frameshift_variant,-2,0.999739,Pathogenic,False
14759,1194553097,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227702385,SLC19A3,T,A,C:0.0000165:22:GnomAD_exomes|C:0.:0:ALFA,intron_variant,-2,0.473579,Pathogenic,True
15415,1240050000,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,delins,227701709,SLC19A3,AGAGAAGGAGGCAAG,AG,AG:0.00008:1:ALFA,intron_variant,-2,0.561789,Pathogenic,True
15866,1272375245,MDCYRTSLSSSWIYPTVILCLFGIFSMMRPSEPFLIPYLSGPDKNL...,snv,227702249,SLC19A3,A,T,T:0.0000007:1:GnomAD_exomes,5_prime_UTR_variant;coding_sequence_variant;mi...,-2,0.490255,Pathogenic,False
16361,1306897813,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227703432,SLC19A3,A,T,T:0.000008:2:TOPMED|T:0.:0:ALFA,intron_variant,-2,0.491174,Pathogenic,True
16600,1322524231,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227698807,SLC19A3,C,T,T:0.000002:1:GnomAD_exomes|T:0.000007:1:GnomAD...,stop_gained;coding_sequence_variant,-2,0.823931,Pathogenic,False
17079,1355622023,MDCYRTSLSSSGFTPL,delins,227702286,SLC19A3,G,-,NaN,frameshift_variant;coding_sequence_variant;5_p...,-2,0.999311,Pathogenic,False
18662,1459307431,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,ins,227698973,SLC19A3,-,A,A:0.000019:5:TOPMED|A:0.:0:ALFA,frameshift_variant;coding_sequence_variant,-2,0.888512,Pathogenic,False
19551,1574560714,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227699478,SLC19A3,G,T,A:0.000002:1:GnomAD_exomes|T:0.000546:1:Korea1K,stop_gained;synonymous_variant;coding_sequence...,-2,0.913073,Pathogenic,False
20529,1695095409,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,delins,227688263,SLC19A3,-,C,CCC:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.992292,Pathogenic,False
21742,1695552369,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,del,227698875,SLC19A3,G,-,-:0.000004:1:TOPMED|-:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.900923,Pathogenic,False
21746,1695554071,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227698921,SLC19A3,C,T,G:0.000001:1:GnomAD_exomes|T:0.000007:1:GnomAD...,coding_sequence_variant;stop_gained;missense_v...,-2,0.912061,Pathogenic,False
21747,1695554660,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,delins,227698928,SLC19A3,-,A,AAAAAA:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.899839,Pathogenic,False
21750,1695558084,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227698973,SLC19A3,G,A,C:0.000002:1:GnomAD_exomes|A:0.000004:1:TOPMED...,coding_sequence_variant;stop_gained;missense_v...,-2,0.881536,Pathogenic,False
21768,1695577738,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227699307,SLC19A3,G,C,C:0.000007:1:GnomAD_genomes,coding_sequence_variant;stop_gained,-2,0.909976,Pathogenic,False
21771,1695580786,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227699346,SLC19A3,G,C,C:0.00005:1:ALFA,coding_sequence_variant;stop_gained,-2,0.474778,Pathogenic,False
22101,1695726256,MDCYRTSLSSSWIYPTVILCLFGFFSRMRPSEPFLIPYLSGPDKNL...,snv,227702239,SLC19A3,A,C,C:0.000003:2:GnomAD_exomes|G:0.000007:1:GnomAD...,coding_sequence_variant;5_prime_UTR_variant;mi...,-2,0.511551,Pathogenic,False
22126,1695739836,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,delins,227702465,SLC19A3,CC,-,-:0.:0:GnomAD_exomes|C:0.:0:ALFA,intron_variant,-2,0.490823,Pathogenic,True
22188,1695762306,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227702972,SLC19A3,T,A,A:0.00009:1:ALFA,intron_variant,-2,0.546032,Pathogenic,True
22191,1695764099,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227703006,SLC19A3,G,A,A:0.000004:1:TOPMED|A:0.:0:ALFA,intron_variant,-2,0.529207,Pathogenic,True
22233,1695782501,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227703340,SLC19A3,G,A,A:0.000007:1:GnomAD_genomes|A:0.000004:1:TOPME...,intron_variant,-2,0.620086,Pathogenic,True
22918,1696030960,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227708563,SLC19A3,A,T,T:0.:0:ALFA,upstream_transcript_variant;genic_upstream_tra...,-2,0.418235,Pathogenic,True
25651,2470553244,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,delins,227687564,SLC19A3,A,-,-:0.000002:1:GnomAD_exomes|-:0.000013:1:TOMMO,coding_sequence_variant;frameshift_variant,-2,0.333720,Pathogenic,False
25652,2470553256,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,delins,227687567,SLC19A3,-,T,T:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.459010,Pathogenic,False
25753,2470555057,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,delins,227688244,SLC19A3,A,-,-:0.000003:2:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.858658,Pathogenic,False
26016,2470568213,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227696038,SLC19A3,C,T,NaN,stop_gained;coding_sequence_variant;missense_v...,-2,0.986516,Pathogenic,False
26157,2470572729,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227698835,SLC19A3,G,A,NaN,stop_gained;coding_sequence_variant;missense_v...,-2,0.749042,Pathogenic,False
26171,2470572883,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,delins,227698879,SLC19A3,A,-,-:0.000001:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.930300,Pathogenic,False
26189,2470573232,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,delins,227699000,SLC19A3,TGAGT,T,-:0.000001:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.977549,Pathogenic,False
26508,2470580813,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLISQNPIFIWTR,delins,227702213,SLC19A3,-,TTTTGTGAAA,AATTTTGTGA:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant;5_p...,-2,0.996794,Pathogenic,False
26509,2470580853,MDCYRTSLSSSWIYPTVILCLFGFFSEPFLIPYLSGPDKNLTSAEI...,delins,227702227,SLC19A3,GAGGGTCTCATCATGGAG,GAG,-:0.000002:1:GnomAD_exomes,inframe_deletion;coding_sequence_variant;5_pri...,-2,0.553266,Pathogenic,False
26510,2470580873,MDCYRTSLSSSWIYPTVILCLFGFFSMM,snv,227702234,SLC19A3,T,A,A:0.000002:1:GnomAD_exomes,stop_gained;coding_sequence_variant;5_prime_UT...,-2,0.997703,Pathogenic,False
26516,2470580926,MDCYRTSLSSSWIYPTVILCLFGLFGFLHDETLRTIPYPIFIWTR,delins,227702249,SLC19A3,-,CCAAATA,ACCAAAT:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant;5_p...,-2,0.996872,Pathogenic,False
26520,2470580992,MDCYRTSLSSSWIYSTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227702276,SLC19A3,G,A,A:0.0000021:3:GnomAD_exomes|A:0.0000129:1:TOMMO,coding_sequence_variant;missense_variant;5_pri...,-2,0.451138,Pathogenic,False
26522,2470581014,MDCYRTSLSSS,snv,227702284,SLC19A3,C,T,T:0.:0:GnomAD_exomes,stop_gained;coding_sequence_variant;5_prime_UT...,-2,0.996329,Pathogenic,False
26524,2470581025,MDCYRTSLSSSVLDLPHCDPLLIWFFLHDETLRTIPYPIFIWTR,delins,227702287,SLC19A3,-,AACT,AACT:0.000001:1:GnomAD_exomes,stop_gained;coding_sequence_variant;5_prime_UT...,-2,0.995153,Pathogenic,False
28572,745538722,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227699396,SLC19A3,G,A,T:0.000008:1:ExAC,missense_variant;coding_sequence_variant;stop_...,-2,0.718970,Pathogenic,False
28690,751334362,MDCYRTSLSSSWIYPTVILCLFGFFSMMKPSEPFLIPYLSGPDKNL...,snv,227702233,SLC19A3,C,T,T:0.000008:1:ExAC,5_prime_UTR_variant;coding_sequence_variant;mi...,-2,0.490122,Pathogenic,False
28859,758769189,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227699461,SLC19A3,A,T,G:0.000008:1:ExAC,coding_sequence_variant;stop_gained;missense_v...,-2,0.865893,Pathogenic,False
28927,761983238,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227698799,SLC19A3,T,A,A:0.000008:1:ExAC|A:0.000003:2:GnomAD_exomes,coding_sequence_variant;stop_gained,-2,0.873663,Pathogenic,False
28973,764631687,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227703210,SLC19A3,A,G,G:0.:0:ALSPAC|G:0.000013:2:GnomAD_genomes|G:0....,intron_variant,-2,0.550482,Pathogenic,True
28982,765014189,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227699289,SLC19A3,G,T,T:0.000041:5:ExAC|T:0.003821:7:Korea1K,coding_sequence_variant;stop_gained,-2,0.968980,Pathogenic,False

In [12]:
pathogenic_new_model.drop(columns=['protein_sequence'], inplace=True)
pathogenic_old_model.drop(columns=['protein_sequence'], inplace=True)

/tmp/ipykernel_44055/2808208366.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pathogenic_new_model.drop(columns=['protein_sequence'], inplace=True)
/tmp/ipykernel_44055/2808208366.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pathogenic_old_model.drop(columns=['protein_sequence'], inplace=True)

In [13]:
pathogenic_new_model.to_csv("results/pathogenic_new_model.csv", index=False)
pathogenic_old_model.to_csv("results/pathogenic_old_model.csv", index=False)

In [14]:
likely_pathogenic_old_model = old_model[old_model['Predicted_Label_Display'] == 'Likely Pathogenic']

In [15]:
likely_pathogenic_old_model.iloc[:50]

,snp_id,protein_sequence,variant_type,position,gene,original,mutant,frequency,function_class,Predicted_Label_Original,Prediction_Confidence,Predicted_Label_Display,normal_seq
2445,1001853470,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477531,SLC19A2,T,C,C:0.000007:1:GnomAD_genomes|C:0.000004:1:TOPME...,coding_sequence_variant;missense_variant;intro...,-1,0.835166,Likely Pathogenic,False
2447,1002305755,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477958,SLC19A2,G,C,NaN,intron_variant,-1,0.970991,Likely Pathogenic,True
2458,1003505341,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169465859,SLC19A2,G,T,T:0.0000014:2:GnomAD_exomes|T:0.0000134:2:Gnom...,coding_sequence_variant;missense_variant,-1,0.565852,Likely Pathogenic,False
2472,1005039064,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169467897,SLC19A2,C,T,G:0.:0:ALFA,intron_variant,-1,0.536493,Likely Pathogenic,True
2489,1006913766,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169472686,SLC19A2,C,T,NaN,intron_variant,-1,0.551074,Likely Pathogenic,True
2490,1007033606,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480812,SLC19A2,T,A,NaN,intron_variant,-1,0.996402,Likely Pathogenic,True
2496,1008478717,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169466621,SLC19A2,C,T,T:0.000007:1:GnomAD_genomes|T:0.:0:ALFA,intron_variant,-1,0.472740,Likely Pathogenic,True
2521,1011324862,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169465326,SLC19A2,G,A,NaN,3_prime_UTR_variant,-1,0.697781,Likely Pathogenic,True
2567,1016320124,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169478301,SLC19A2,G,A,A:0.00002:3:GnomAD_genomes|A:0.00003:8:TOPMED|...,intron_variant,-1,0.927981,Likely Pathogenic,True
2591,1018486572,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480545,SLC19A2,C,T,NaN,intron_variant,-1,0.981689,Likely Pathogenic,True
2593,1018549401,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480822,SLC19A2,C,T,T:0.000101:15:GnomAD_genomes|T:0.000013:1:TOMM...,intron_variant,-1,0.971601,Likely Pathogenic,True
2612,1020675801,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169478435,SLC19A2,C,T,T:0.000223:1:Estonian|T:0.000142:21:GnomAD_gen...,intron_variant,-1,0.530971,Likely Pathogenic,True
2615,1021035057,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470526,SLC19A2,G,T,T:0.000027:4:GnomAD_genomes|T:0.:0:ALFA,intron_variant,-1,0.847325,Likely Pathogenic,True
2632,1022350269,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480476,SLC19A2,C,T,T:0.000004:1:TOPMED|T:0.:0:ALFA,intron_variant,-1,0.719784,Likely Pathogenic,True
2636,1022724657,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169479864,SLC19A2,G,A,C:0.000013:2:GnomAD_genomes|C:0.:0:ALFA,intron_variant,-1,0.928360,Likely Pathogenic,True
2637,1022724657,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169479864,SLC19A2,G,C,C:0.000013:2:GnomAD_genomes|C:0.:0:ALFA,intron_variant,-1,0.479128,Likely Pathogenic,True
2644,1023423314,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169467281,SLC19A2,T,G,G:0.000011:3:TOPMED|G:0.:0:ALFA,intron_variant,-1,0.927073,Likely Pathogenic,True
2680,1028030681,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470851,SLC19A2,C,G,G:0.000007:1:GnomAD_genomes|G:0.000004:1:TOPME...,intron_variant,-1,0.995553,Likely Pathogenic,True
2691,1029114265,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169482592,SLC19A2,A,C,C:0.000034:5:GnomAD_genomes|C:0.00003:8:TOPMED...,intron_variant,-1,0.706238,Likely Pathogenic,True
2700,1029941510,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480275,SLC19A2,T,C,NaN,intron_variant,-1,0.988497,Likely Pathogenic,True
2716,1031664096,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169485511,SLC19A2,A,C,C:0.0000008:1:GnomAD_exomes|C:0.0004147:3:Kore...,intron_variant,-1,0.752763,Likely Pathogenic,True
2722,1032033979,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169481897,SLC19A2,G,A,A:0.000007:1:GnomAD_genomes|A:0.000026:7:TOPME...,intron_variant,-1,0.464398,Likely Pathogenic,True
2730,1032519430,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477589,SLC19A2,G,T,T:0.000003:2:GnomAD_exomes,intron_variant;coding_sequence_variant;missens...,-1,0.792398,Likely Pathogenic,False
2751,1035361467,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169481718,SLC19A2,A,G,NaN,intron_variant,-1,0.989233,Likely Pathogenic,True
2756,1035877266,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169481290,SLC19A2,T,C,C:0.000013:2:GnomAD_genomes|C:0.000011:3:TOPME...,intron_variant,-1,0.711362,Likely Pathogenic,True
2760,1036568273,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477925,SLC19A2,T,A,A:0.000013:2:GnomAD_genomes|A:0.000015:4:TOPME...,intron_variant,-1,0.917627,Likely Pathogenic,True
2777,1038479954,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169464837,SLC19A2,T,C,C:0.000019:5:TOPMED|C:0.:0:ALFA,3_prime_UTR_variant,-1,0.893649,Likely Pathogenic,True
2798,1040223119,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480986,SLC19A2,A,T,T:0.000007:1:GnomAD_genomes|T:0.000011:3:TOPME...,intron_variant,-1,0.669254,Likely Pathogenic,True
2823,1042685073,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169482356,SLC19A2,A,G,G:0.000312:2:1000Genomes_30X|G:0.000261:39:Gno...,intron_variant,-1,0.923291,Likely Pathogenic,True
2824,1042737233,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169482687,SLC19A2,A,G,G:0.000008:2:TOPMED|G:0.:0:ALFA,intron_variant,-1,0.905768,Likely Pathogenic,True
2868,1048178231,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468307,SLC19A2,A,G,G:0.000005:3:GnomAD_exomes|G:0.000007:1:GnomAD...,intron_variant,-1,0.890593,Likely Pathogenic,True
2880,1049847878,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169479827,SLC19A2,T,G,NaN,intron_variant,-1,0.793628,Likely Pathogenic,True
2897,1051745914,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169479610,SLC19A2,G,T,T:0.:0:ALFA,intron_variant,-1,0.916280,Likely Pathogenic,True
2904,1052755025,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474824,SLC19A2,T,C,NaN,intron_variant,-1,0.702332,Likely Pathogenic,True
2927,1054210391,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477824,SLC19A2,G,T,T:0.0000016:2:GnomAD_exomes|T:0.0000135:2:Gnom...,intron_variant,-1,0.869159,Likely Pathogenic,True
2932,1054756181,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169485466,SLC19A2,G,C,C:0.000008:2:TOPMED|C:0.:0:ALFA,intron_variant,-1,0.628133,Likely Pathogenic,True
2939,1055423300,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169465308,SLC19A2,C,T,T:0.000008:2:TOPMED|T:0.:0:ALFA,3_prime_UTR_variant,-1,0.432319,Likely Pathogenic,True
2941,1055513399,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169471880,SLC19A2,T,G,C:0.000027:4:GnomAD_genomes|C:0.00003:8:TOPMED...,intron_variant,-1,0.480482,Likely Pathogenic,True
2942,1055627732,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169472317,SLC19A2,A,C,NaN,intron_variant,-1,0.505988,Likely Pathogenic,True
2944,1055726292,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169478268,SLC19A2,G,C,C:0.000008:2:TOPMED|C:0.:0:ALFA,intron_variant,-1,0.967704,Likely Pathogenic,True
2949,1056135962,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480657,SLC19A2,A,C,C:0.000004:1:TOPMED|C:0.:0:ALFA,intron_variant,-1,0.731227,Likely Pathogenic,True
2965,1057390644,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169482324,SLC19A2,G,A,NaN,intron_variant,-1,0.735217,Likely Pathogenic,True
2971,111324338,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480395,SLC19A2,C,T,NaN,intron_variant,-1,0.914213,Likely Pathogenic,True
2977,112140613,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477835,SLC19A2,T,C,C:0.0000033:4:GnomAD_exomes,intron_variant,-1,0.954487,Likely Pathogenic,True
2979,112215556,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470869,SLC19A2,A,G,G:0.005591:28:1000Genomes|G:0.00609:39:1000Gen...,intron_variant,-1,0.822373,Likely Pathogenic,True
3003,114400094,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169481597,SLC19A2,G,A,A:0.001:5:1000Genomes|A:0.00094:6:1000Genomes_...,intron_variant,-1,0.476503,Likely Pathogenic,True
3004,114400094,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169481597,SLC19A2,G,C,A:0.001:5:1000Genomes|A:0.00094:6:1000Genomes_...,intron_variant,-1,0.859929,Likely Pathogenic,True
3017,1157995859,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169482344,SLC19A2,A,G,G:0.000007:1:GnomAD_genomes|G:0.:0:ALFA,intron_variant,-1,0.969895,Likely Pathogenic,True
3045,1160067049,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169463941,SLC19A2,T,C,C:0.000007:1:GnomAD_genomes,3_prime_UTR_variant,-1,0.571024,Likely Pathogenic,True
3065,1162493288,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169482379,SLC19A2,A,C,C:0.000007:1:GnomAD_genomes,intron_variant,-1,0.518500,Likely Pathogenic,True

In [16]:
likely_pathogenic_new_model = new_model[new_model['Predicted_Label_Display'] == 'Likely Pathogenic']
likely_pathogenic_new_model.iloc[:50]

,snp_id,protein_sequence,variant_type,position,gene,original,mutant,frequency,function_class,Predicted_Label_Original,Prediction_Confidence,Predicted_Label_Display,normal_seq
2615,1021035057,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470526,SLC19A2,G,T,T:0.000027:4:GnomAD_genomes|T:0.:0:ALFA,intron_variant,-1,0.646422,Likely Pathogenic,True
2680,1028030681,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470851,SLC19A2,C,G,G:0.000007:1:GnomAD_genomes|G:0.000004:1:TOPME...,intron_variant,-1,0.384446,Likely Pathogenic,True
2751,1035361467,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169481718,SLC19A2,A,G,NaN,intron_variant,-1,0.370119,Likely Pathogenic,True
2868,1048178231,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468307,SLC19A2,A,G,G:0.000005:3:GnomAD_exomes|G:0.000007:1:GnomAD...,intron_variant,-1,0.557148,Likely Pathogenic,True
2979,112215556,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470869,SLC19A2,A,G,G:0.005591:28:1000Genomes|G:0.00609:39:1000Gen...,intron_variant,-1,0.466117,Likely Pathogenic,True
3139,1170561910,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169469971,SLC19A2,G,A,T:0.00005:1:ALFA,coding_sequence_variant;synonymous_variant,-1,0.407583,Likely Pathogenic,True
3344,1195909186,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480311,SLC19A2,T,C,C:0.000019:5:TOPMED|C:0.:0:ALFA,intron_variant,-1,0.384239,Likely Pathogenic,True
3380,1198926832,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470861,SLC19A2,T,C,C:0.000013:2:GnomAD_genomes|C:0.000008:2:TOPME...,intron_variant,-1,0.540118,Likely Pathogenic,True
3873,1252755149,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470868,SLC19A2,G,C,C:0.000446:2:Estonian|C:0.000007:1:GnomAD_geno...,intron_variant,-1,0.474728,Likely Pathogenic,True
3904,1257494661,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477571,SLC19A2,A,T,T:0.000002:1:GnomAD_exomes,missense_variant;coding_sequence_variant;intro...,-1,0.379263,Likely Pathogenic,False
4176,1284347696,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468729,SLC19A2,T,A,C:0.000004:1:TOPMED|C:0.000094:1:ALFA,coding_sequence_variant;missense_variant,-1,0.465577,Likely Pathogenic,False
4296,1298766894,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169469925,SLC19A2,C,T,T:0.000007:1:GnomAD_genomes|T:0.:0:ALFA,intron_variant,-1,0.472174,Likely Pathogenic,True
4409,1316461339,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468705,SLC19A2,C,T,NaN,coding_sequence_variant;missense_variant,-1,0.477125,Likely Pathogenic,False
4587,1333282774,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468645,SLC19A2,T,C,NaN,coding_sequence_variant;missense_variant,-1,0.509932,Likely Pathogenic,False
4684,1343844974,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169469417,SLC19A2,G,A,A:0.000004:1:TOPMED|A:0.:0:ALFA,intron_variant,-1,0.584466,Likely Pathogenic,True
4717,1348431253,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169469618,SLC19A2,A,G,G:0.000007:1:GnomAD_genomes|G:0.000004:1:TOPME...,intron_variant,-1,0.403889,Likely Pathogenic,True
4718,1348631348,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480579,SLC19A2,T,C,C:0.000007:1:GnomAD_genomes|C:0.000138:1:Korea...,intron_variant,-1,0.426800,Likely Pathogenic,True
4723,1348748853,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169469599,SLC19A2,T,A,A:0.000004:1:TOPMED|C:0.:0:ALFA,intron_variant,-1,0.564526,Likely Pathogenic,True
4724,1348748853,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169469599,SLC19A2,T,C,A:0.000004:1:TOPMED|C:0.:0:ALFA,intron_variant,-1,0.608913,Likely Pathogenic,True
4882,1368523747,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468254,SLC19A2,T,G,G:0.000007:1:GnomAD_genomes|G:0.:0:ALFA,splice_acceptor_variant,-1,0.360990,Likely Pathogenic,True
4936,1376334886,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468860,SLC19A2,C,A,A:0.000002:1:GnomAD_exomes,intron_variant,-1,0.422924,Likely Pathogenic,True
4969,1379728212,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169469965,SLC19A2,C,G,NaN,synonymous_variant;coding_sequence_variant,-1,0.613316,Likely Pathogenic,True
4972,1379819243,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468085,SLC19A2,C,T,A:0.000002:1:GnomAD_exomes|T:0.:0:ALFA,intron_variant,-1,0.520991,Likely Pathogenic,True
4977,1379897518,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470447,SLC19A2,T,A,C:0.:0:ALFA,intron_variant,-1,0.436653,Likely Pathogenic,True
5116,1396000423,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468797,SLC19A2,G,T,T:0.000002:1:GnomAD_exomes|A:0.000342:1:KOREAN,missense_variant;coding_sequence_variant,-1,0.516631,Likely Pathogenic,False
5301,1411492910,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169469483,SLC19A2,T,C,C:0.000008:2:TOPMED|C:0.000071:1:ALFA,intron_variant,-1,0.782299,Likely Pathogenic,True
5548,1438181961,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169467564,SLC19A2,T,C,C:0.000007:1:GnomAD_genomes|C:0.000004:1:TOPME...,intron_variant,-1,0.473878,Likely Pathogenic,True
5677,1453311342,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470952,SLC19A2,G,A,A:0.000004:1:TOPMED|A:0.:0:ALFA,intron_variant,-1,0.371371,Likely Pathogenic,True
5789,1464674227,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169467567,SLC19A2,A,C,C:0.000013:2:GnomAD_genomes|C:0.000015:4:TOPME...,intron_variant,-1,0.340757,Likely Pathogenic,True
5843,1470266921,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169469429,SLC19A2,G,C,T:0.:0:ALFA,intron_variant,-1,0.454896,Likely Pathogenic,True
5844,1470266921,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169469429,SLC19A2,G,T,T:0.:0:ALFA,intron_variant,-1,0.507267,Likely Pathogenic,True
6173,1557892087,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477681,SLC19A2,T,C,C:0.:0:GnomAD_exomes,missense_variant;intron_variant;coding_sequenc...,-1,0.375538,Likely Pathogenic,False
6291,1571532322,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169469620,SLC19A2,A,G,G:0.000008:2:TOPMED|G:0.:0:ALFA,intron_variant,-1,0.440836,Likely Pathogenic,True
6423,1571539896,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480592,SLC19A2,A,G,C:0.0022:4:Korea1K,intron_variant,-1,0.693983,Likely Pathogenic,True
6918,1658014456,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169467273,SLC19A2,A,T,T:0.000004:1:TOPMED|T:0.:0:ALFA,intron_variant,-1,0.417101,Likely Pathogenic,True
6928,1658016106,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169467361,SLC19A2,C,G,G:0.000008:2:TOPMED|G:0.:0:ALFA,intron_variant,-1,0.457950,Likely Pathogenic,True
6953,1658065806,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169467562,SLC19A2,T,C,C:0.00014:1:Korea4K|C:0.00001:1:TOMMO,intron_variant,-1,0.501185,Likely Pathogenic,True
7031,1658080198,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468197,SLC19A2,T,A,A:0.000007:1:GnomAD_genomes|A:0.:0:ALFA,coding_sequence_variant;missense_variant,-1,0.487816,Likely Pathogenic,False
7067,1658089016,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468508,SLC19A2,T,C,C:0.000008:2:TOPMED|G:0.:0:ALFA,intron_variant,-1,0.592361,Likely Pathogenic,True
7076,1658089816,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468557,SLC19A2,A,-,-:0.00001:1:TOMMO,intron_variant,-1,0.681818,Likely Pathogenic,True
7082,1658091552,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468649,SLC19A2,T,C,C:0.000008:2:TOPMED|C:0.:0:ALFA,coding_sequence_variant;missense_variant,-1,0.535105,Likely Pathogenic,False
7084,1658092094,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468657,SLC19A2,T,A,A:0.000002:1:GnomAD_exomes|A:0.000077:6:TOMMO,coding_sequence_variant;missense_variant,-1,0.592126,Likely Pathogenic,False
7095,1658097946,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468825,SLC19A2,C,T,T:0.00028:2:Korea4K|T:0.00003:2:TOMMO,coding_sequence_variant;missense_variant,-1,0.513061,Likely Pathogenic,False
7106,1658101684,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468944,SLC19A2,A,T,T:0.000003:2:GnomAD_exomes|T:0.000013:2:GnomAD...,intron_variant,-1,0.505573,Likely Pathogenic,True
7108,1658101842,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468947,SLC19A2,G,T,C:0.000007:1:GnomAD_genomes|C:0.000008:2:TOPME...,intron_variant,-1,0.661357,Likely Pathogenic,True
7158,1658112133,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169469368,SLC19A2,A,T,T:0.000004:1:TOPMED|T:0.:0:ALFA,intron_variant,-1,0.327922,Likely Pathogenic,True
7173,1658115340,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169469538,SLC19A2,A,C,NaN,intron_variant,-1,0.526610,Likely Pathogenic,True
7178,1658116487,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169469605,SLC19A2,T,C,C:0.000007:1:GnomAD_genomes|C:0.:0:ALFA,intron_variant,-1,0.665084,Likely Pathogenic,True
7179,1658116661,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169469619,SLC19A2,G,C,C:0.:0:ALFA,intron_variant,-1,0.340331,Likely Pathogenic,True
7184,1658117029,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169469633,SLC19A2,A,G,G:0.000004:1:TOPMED|G:0.:0:ALFA,intron_variant,-1,0.447788,Likely Pathogenic,True

In [17]:
pathogenic_newest_model = newest_model[newest_model['Predicted_Label_Display'] == 'Likely Pathogenic']
pathogenic_newest_model.head(50)

,snp_id,protein_sequence,variant_type,position,gene,original,mutant,frequency,function_class,Predicted_Label_Original,Prediction_Confidence,Predicted_Label_Display,normal_seq
2490,1007033606,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480812,SLC19A2,T,A,NaN,intron_variant,-1,0.977321,Likely Pathogenic,True
2593,1018549401,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480822,SLC19A2,C,T,T:0.000101:15:GnomAD_genomes|T:0.000013:1:TOMM...,intron_variant,-1,0.763286,Likely Pathogenic,True
2651,1024192776,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169479556,SLC19A2,G,A,A:0.000013:2:GnomAD_genomes|A:0.000026:7:TOPME...,intron_variant,-1,0.999982,Likely Pathogenic,True
2680,1028030681,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470851,SLC19A2,C,G,G:0.000007:1:GnomAD_genomes|G:0.000004:1:TOPME...,intron_variant,-1,0.896478,Likely Pathogenic,True
3128,1169422753,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477628,SLC19A2,A,G,G:0.000002:1:GnomAD_exomes|G:0.:0:KOREAN|C:0.0...,intron_variant;coding_sequence_variant;missens...,-1,0.677535,Likely Pathogenic,False
3152,1171659497,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474025,SLC19A2,T,A,G:0.000007:1:GnomAD_genomes|G:0.:0:ALFA,intron_variant,-1,0.521272,Likely Pathogenic,True
3345,1195909186,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480311,SLC19A2,T,A,C:0.000019:5:TOPMED|C:0.:0:ALFA,intron_variant,-1,0.689358,Likely Pathogenic,True
3463,1207369517,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169478827,SLC19A2,T,C,C:0.:0:ALFA,intron_variant,-1,0.813105,Likely Pathogenic,True
3872,1251759726,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169479549,SLC19A2,A,T,T:0.000011:3:TOPMED|T:0.:0:ALFA,intron_variant,-1,0.821330,Likely Pathogenic,True
3904,1257494661,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477571,SLC19A2,A,T,T:0.000002:1:GnomAD_exomes,missense_variant;coding_sequence_variant;intro...,-1,0.747503,Likely Pathogenic,False
4139,1281465043,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480559,SLC19A2,G,A,A:0.000156:1:1000Genomes_30X|A:0.000007:1:Gnom...,intron_variant,-1,0.510141,Likely Pathogenic,True
4514,1326664794,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480574,SLC19A2,A,G,G:0.000004:1:TOPMED|G:0.:0:ALFA,intron_variant,-1,0.598422,Likely Pathogenic,True
4718,1348631348,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480579,SLC19A2,T,C,C:0.000007:1:GnomAD_genomes|C:0.000138:1:Korea...,intron_variant,-1,0.998618,Likely Pathogenic,True
5637,1447611272,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169481646,SLC19A2,T,C,C:0.000004:1:TOPMED|C:0.:0:ALFA,intron_variant,-1,0.790162,Likely Pathogenic,True
6356,1571535894,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169474477,SLC19A2,CAC,C,-:0.0005:1:Korea1K,intron_variant,-1,0.972113,Likely Pathogenic,True
6423,1571539896,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480592,SLC19A2,A,G,C:0.0022:4:Korea1K,intron_variant,-1,0.999973,Likely Pathogenic,True
6424,1571539896,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480592,SLC19A2,A,C,C:0.0022:4:Korea1K,intron_variant,-1,0.792732,Likely Pathogenic,True
6444,1571540965,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169482479,SLC19A2,T,A,A:0.0003:1:KOREAN,intron_variant,-1,0.559334,Likely Pathogenic,True
7022,1658076107,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468111,SLC19A2,C,A,T:0.00001:1:TOMMO,coding_sequence_variant;synonymous_variant;mis...,-1,0.900388,Likely Pathogenic,False
7294,1658155092,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470852,SLC19A2,T,C,C:0.000007:1:GnomAD_genomes|C:0.:0:ALFA,intron_variant,-1,0.937048,Likely Pathogenic,True
7708,1658258405,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474241,SLC19A2,A,C,C:0.:0:ALFA,intron_variant,-1,0.519802,Likely Pathogenic,True
7715,1658259505,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474291,SLC19A2,C,T,T:0.:0:ALFA,intron_variant,-1,0.998920,Likely Pathogenic,True
7735,1658262958,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474421,SLC19A2,A,G,NaN,intron_variant,-1,0.994339,Likely Pathogenic,True
7746,1658265651,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474501,SLC19A2,C,G,G:0.:0:ALFA,intron_variant,-1,0.724662,Likely Pathogenic,True
7749,1658266346,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474534,SLC19A2,C,T,T:0.000004:1:TOPMED|T:0.:0:ALFA,intron_variant,-1,0.999992,Likely Pathogenic,True
8102,1658357249,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477703,SLC19A2,G,A,A:0.000001:1:GnomAD_exomes|A:0.000026:2:TOMMO|...,coding_sequence_variant;intron_variant;missens...,-1,0.875062,Likely Pathogenic,False
8262,1658385619,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169478854,SLC19A2,G,A,A:0.000004:1:TOPMED|A:0.:0:ALFA,intron_variant,-1,0.644503,Likely Pathogenic,True
8331,1658395432,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169479465,SLC19A2,T,C,C:0.000004:1:TOPMED|C:0.:0:ALFA,intron_variant,-1,0.995417,Likely Pathogenic,True
8452,1658425051,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480729,SLC19A2,T,C,C:0.00001:1:TOMMO,intron_variant,-1,0.690937,Likely Pathogenic,True
8454,1658425155,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480733,SLC19A2,A,G,G:0.:0:ALFA,intron_variant,-1,0.876457,Likely Pathogenic,True
8465,1658426475,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480801,SLC19A2,G,A,A:0.0001:8:TOMMO,intron_variant,-1,0.592040,Likely Pathogenic,True
8537,1658443646,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169481447,SLC19A2,C,A,A:0.000004:1:TOPMED|A:0.:0:ALFA,intron_variant,-1,0.584042,Likely Pathogenic,True
8554,1658446004,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169481546,SLC19A2,A,C,C:0.00003:2:TOMMO|C:0.:0:ALFA,intron_variant,-1,0.551343,Likely Pathogenic,True
8578,1658450419,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169481876,SLC19A2,A,G,G:0.000004:1:TOPMED|G:0.:0:ALFA,intron_variant,-1,0.555120,Likely Pathogenic,True
9646,2101784322,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169481578,SLC19A2,T,C,C:0.00001:1:TOMMO,intron_variant,-1,0.654420,Likely Pathogenic,True
9861,2526229214,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169465965,SLC19A2,C,T,T:0.000002:1:GnomAD_exomes,missense_variant;coding_sequence_variant,-1,0.614963,Likely Pathogenic,False
10025,2526235580,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468481,SLC19A2,T,C,C:0.000006:3:GnomAD_exomes,intron_variant,-1,0.775772,Likely Pathogenic,True
10115,2526236993,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468928,SLC19A2,A,T,T:0.000002:1:GnomAD_exomes,intron_variant,-1,0.633034,Likely Pathogenic,True
10398,2526255772,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477154,SLC19A2,C,G,G:0.000002:1:GnomAD_exomes,intron_variant;splice_donor_variant,-1,0.831187,Likely Pathogenic,True
10469,2526257582,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477611,SLC19A2,A,G,G:0.000002:1:GnomAD_exomes,intron_variant;coding_sequence_variant;synonym...,-1,0.634774,Likely Pathogenic,True
10476,2526257694,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477666,SLC19A2,G,A,A:0.000001:1:GnomAD_exomes,missense_variant;intron_variant;coding_sequenc...,-1,0.737227,Likely Pathogenic,False
10482,2526257789,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477684,SLC19A2,T,G,G:0.00001:1:TOMMO,missense_variant;intron_variant;coding_sequenc...,-1,0.732113,Likely Pathogenic,False
10569,2526263950,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169480588,SLC19A2,C,T,T:0.00003:2:TOMMO,intron_variant,-1,0.916496,Likely Pathogenic,True
10589,2526266791,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169482136,SLC19A2,G,T,T:0.00003:2:TOMMO,intron_variant,-1,0.779776,Likely Pathogenic,True
10745,2526274972,MDVPGPVSRRAAAAAATRPVLLRTARVRRECWFLPTALLCAYGFFA...,delins,169485716,SLC19A2,-,TGGCCG,GTGGCC:0.000001:1:GnomAD_exomes,inframe_insertion;coding_sequence_variant,-1,0.604058,Likely Pathogenic,False
11126,540395036,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169479463,SLC19A2,T,A,A:0.0002:1:1000Genomes|A:0.000312:2:1000Genome...,intron_variant,-1,0.728119,Likely Pathogenic,True
11146,543259451,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474399,SLC19A2,G,T,C:0.000007:1:GnomAD_genomes|G:0.5:1:SGDP_PRJ|C...,intron_variant,-1,0.893201,Likely Pathogenic,True
11147,543259451,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169474399,SLC19A2,G,C,C:0.000007:1:GnomAD_genomes|G:0.5:1:SGDP_PRJ|C...,intron_variant,-1,0.502599,Likely Pathogenic,True
11598,752357863,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477697,SLC19A2,A,G,G:0.000017:2:ExAC|G:0.000013:8:GnomAD_exomes|G...,missense_variant;coding_sequence_variant;intro...,-1,0.719537,Likely Pathogenic,False
11720,762045277,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477627,SLC19A2,C,G,G:0.000008:1:ExAC|G:0.000003:2:GnomAD_exomes|G...,missense_variant;coding_sequence_variant;intro...,-1,0.996381,Likely Pathogenic,False

In [18]:
def calculate_label_statistics(df, label="Pathogenic"):
    
    filtered_df = df[df['Predicted_Label_Display'] == label]
    number_of_variants = filtered_df.shape[0]
    number_of_mutated_protien_seq = filtered_df[filtered_df['normal_seq'] == False].shape[0]
    number_of_normal_protien_seq = filtered_df[filtered_df['normal_seq'] == True].shape[0]
    mutated_percentage_to_total = (number_of_mutated_protien_seq / number_of_variants * 100) if number_of_variants > 0 else 0
    average_confidence = filtered_df['Prediction_Confidence'].mean()
    average_confidence_normal = filtered_df[filtered_df['normal_seq'] == True]['Prediction_Confidence'].mean()
    average_confidence_mutated = filtered_df[filtered_df['normal_seq'] == False]['Prediction_Confidence'].mean()

    return {
        "number_of_variants": number_of_variants,
        "number_of_mutated_protien_seq": number_of_mutated_protien_seq,
        "number_of_normal_protien_seq": number_of_normal_protien_seq,
        "mutated_percentage_to_total": mutated_percentage_to_total,
        "average_confidence": average_confidence,
        "average_confidence_normal": average_confidence_normal,
        "average_confidence_mutated": average_confidence_mutated
    }


pathogenic_old_model_stats = calculate_label_statistics(old_model, "Pathogenic")
pathogenic_new_model_stats = calculate_label_statistics(new_model, "Pathogenic")
pathogenic_newest_model_stats = calculate_label_statistics(newest_model, "Pathogenic")
pathogenic_model_4_stats = calculate_label_statistics(model_4, "Pathogenic")
pathogenic_model_5_stats = calculate_label_statistics(model_5, "Pathogenic")
pathogenic_model_6_stats = calculate_label_statistics(model_6, "Pathogenic")

likely_pathogenic_old_model_stats = calculate_label_statistics(old_model, "Likely Pathogenic")
likely_pathogenic_new_model_stats = calculate_label_statistics(new_model, "Likely Pathogenic")
likely_pathogenic_newest_model_stats = calculate_label_statistics(newest_model, "Likely Pathogenic")
likely_pathogenic_model_4_stats = calculate_label_statistics(model_4, "Likely Pathogenic")
likely_pathogenic_model_5_stats = calculate_label_statistics(model_5, "Likely Pathogenic")
likely_pathogenic_model_6_stats = calculate_label_statistics(model_6, "Likely Pathogenic")

benign_old_model_stats = calculate_label_statistics(old_model, "Benign")
benign_new_model_stats = calculate_label_statistics(new_model, "Benign")
benign_newest_model_stats = calculate_label_statistics(newest_model, "Benign")
benign_model_4_stats = calculate_label_statistics(model_4, "Benign")
benign_model_5_stats = calculate_label_statistics(model_5, "Benign")
benign_model_6_stats = calculate_label_statistics(model_6, "Benign")

likely_benign_old_model_stats = calculate_label_statistics(old_model, "Likely Benign")
likely_benign_new_model_stats = calculate_label_statistics(new_model, "Likely Benign")
likely_benign_newest_model_stats = calculate_label_statistics(newest_model, "Likely Benign")
likely_benign_model_4_stats = calculate_label_statistics(model_4, "Likely Benign")
likely_benign_model_5_stats = calculate_label_statistics(model_5, "Likely Benign")
likely_benign_model_6_stats = calculate_label_statistics(model_6, "Likely Benign")

print("pathogenic old model stats")
for stat in pathogenic_old_model_stats:
    print(f"Old Model - {stat}: {pathogenic_old_model_stats[stat]}")
print("=" * 50)

print("pathogenic new model stats")
for stat in pathogenic_new_model_stats:
    print(f"New Model - {stat}: {pathogenic_new_model_stats[stat]}")
print("=" * 50)

print("pathogenic newest model stats")
for stat in pathogenic_newest_model_stats:
    print(f"Newest Model - {stat}: {pathogenic_newest_model_stats[stat]}")
print("=" * 50)

print("Pathogenic Model 4 Stats")
for stat in pathogenic_model_4_stats:
    print(f"Model 4 - {stat}: {pathogenic_model_4_stats[stat]}")
print("=" * 50)

print("Pathogenic Model 5 Stats")
for stat in pathogenic_model_5_stats:
    print(f"Model 5 - {stat}: {pathogenic_model_5_stats[stat]}")
print("=" * 50)

print("pathogenic model 6 stats")
for stat in pathogenic_model_6_stats:
    print(f"Model 6 - {stat}: {pathogenic_model_6_stats[stat]}")
print("=" * 50)

# ===================================================

print("likely pathogenic old model stats")
for stat in likely_pathogenic_old_model_stats:
    print(f"Likely Pathogenic Old Model - {stat}: {likely_pathogenic_old_model_stats[stat]}")
print("=" * 50)

print("likely pathogenic new model stats")
for stat in likely_pathogenic_new_model_stats:
    print(f"Likely Pathogenic New Model - {stat}: {likely_pathogenic_new_model_stats[stat]}")

print("=" * 50)


print("likely pathogenic newest model stats")
for stat in likely_pathogenic_newest_model_stats:
    print(f"Likely Pathogenic Newest Model - {stat}: {likely_pathogenic_newest_model_stats[stat]}")

print("=" * 50)

print("Likely Pathogenic Model 4 Stats")
for stat in likely_pathogenic_model_4_stats:
    print(f"Model 4 - {stat}: {likely_pathogenic_model_4_stats[stat]}")
print("=" * 50)

print("Likely Pathogenic Model 5 Stats")
for stat in likely_pathogenic_model_5_stats:
    print(f"Model 5 - {stat}: {likely_pathogenic_model_5_stats[stat]}")
print("=" * 50)

print("Likely Pathogenic Model 6 Stats")
for stat in likely_pathogenic_model_6_stats:
    print(f"Model 6 - {stat}: {likely_pathogenic_model_6_stats[stat]}")
print("=" * 50)

# ===================================================

print("benign old model stats")
for stat in benign_old_model_stats:
    print(f"Benign Old Model - {stat}: {benign_old_model_stats[stat]}")
print("=" * 50)

print("benign new model stats")
for stat in benign_new_model_stats:
    print(f"Benign New Model - {stat}: {benign_new_model_stats[stat]}")
print("=" * 50)

print("benign newest model stats")
for stat in benign_newest_model_stats:
    print(f"Benign Newest Model - {stat}: {benign_newest_model_stats[stat]}")
print("=" * 50)

print("benign model 4 stats")
for stat in benign_model_4_stats:
    print(f"Model 4 - {stat}: {benign_model_4_stats[stat]}")
print("=" * 50)

print("benign model 5 stats")
for stat in benign_model_5_stats:
    print(f"Model 5 - {stat}: {benign_model_5_stats[stat]}")
print("=" * 50)

print("benign model 6 stats")
for stat in benign_model_6_stats:
    print(f"Model 6 - {stat}: {benign_model_6_stats[stat]}")
print("=" * 50)

# =================================


print("likely benign old model stats")
for stat in likely_benign_old_model_stats:
    print(f"Likely Benign Old Model - {stat}: {likely_benign_old_model_stats[stat]}")
print("=" * 50)

print("likely benign new model stats")
for stat in likely_benign_new_model_stats:
    print(f"Likely Benign New Model - {stat}: {likely_benign_new_model_stats[stat]}")
print("=" * 50)

print("likely benign newest model stats")
for stat in likely_benign_newest_model_stats:
    print(f"Likely Benign Newest Model - {stat}: {likely_benign_newest_model_stats[stat]}")
print("=" * 50)

print("Likely Benign Model 4 Stats")
for stat in likely_benign_model_4_stats:
    print(f"Model 4 - {stat}: {likely_benign_model_4_stats[stat]}")
print("=" * 50)

print("Likely Benign Model 5 Stats")
for stat in likely_benign_model_5_stats:
    print(f"Model 5 - {stat}: {likely_benign_model_5_stats[stat]}")
print("=" * 50)

print("Likely Benign Model 6 Stats")
for stat in likely_benign_model_6_stats:
    print(f"Model 6 - {stat}: {likely_benign_model_6_stats[stat]}")
print("=" * 50)

pathogenic old model stats
Old Model - number_of_variants: 251
Old Model - number_of_mutated_protien_seq: 125
Old Model - number_of_normal_protien_seq: 126
Old Model - mutated_percentage_to_total: 49.800796812749006
Old Model - average_confidence: 0.7514298591633466
Old Model - average_confidence_normal: 0.6228570367460318
Old Model - average_confidence_mutated: 0.8810312641600001
==================================================
pathogenic new model stats
New Model - number_of_variants: 105
New Model - number_of_mutated_protien_seq: 93
New Model - number_of_normal_protien_seq: 12
New Model - mutated_percentage_to_total: 88.57142857142857
New Model - average_confidence: 0.8539132496190477
New Model - average_confidence_normal: 0.5075782499999999
New Model - average_confidence_mutated: 0.8986016366666668
==================================================
pathogenic newest model stats
Newest Model - number_of_variants: 234
Newest Model - number_of_mutated_protien_seq: 114
Newest Model - number_of_normal_protien_seq: 120
Newest Model - mutated_percentage_to_total: 48.717948717948715
Newest Model - average_confidence: 0.8531088866239317
Newest Model - average_confidence_normal: 0.7938893208333333
Newest Model - average_confidence_mutated: 0.9154452716666667
==================================================
Pathogenic Model 4 Stats
Model 4 - number_of_variants: 279
Model 4 - number_of_mutated_protien_seq: 132
Model 4 - number_of_normal_protien_seq: 147
Model 4 - mutated_percentage_to_total: 47.31182795698925
Model 4 - average_confidence: 0.6866204480645162
Model 4 - average_confidence_normal: 0.5626304819727891
Model 4 - average_confidence_mutated: 0.8247001830303031
==================================================
Pathogenic Model 5 Stats
Model 5 - number_of_variants: 202
Model 5 - number_of_mutated_protien_seq: 107
Model 5 - number_of_normal_protien_seq: 95
Model 5 - mutated_percentage_to_total: 52.97029702970298
Model 5 - average_confidence: 0.7355079802475247
Model 5 - average_confidence_normal: 0.5658767661052632
Model 5 - average_confidence_mutated: 0.8861151329906541
==================================================
pathogenic model 6 stats
Model 6 - number_of_variants: 141
Model 6 - number_of_mutated_protien_seq: 112
Model 6 - number_of_normal_protien_seq: 29
Model 6 - mutated_percentage_to_total: 79.43262411347519
Model 6 - average_confidence: 0.7222760261702129
Model 6 - average_confidence_normal: 0.44962504724137936
Model 6 - average_confidence_mutated: 0.7928731546428571
==================================================
likely pathogenic old model stats
Likely Pathogenic Old Model - number_of_variants: 2022
Likely Pathogenic Old Model - number_of_mutated_protien_seq: 364
Likely Pathogenic Old Model - number_of_normal_protien_seq: 1658
Likely Pathogenic Old Model - mutated_percentage_to_total: 18.001978239366963
Likely Pathogenic Old Model - average_confidence: 0.7308950470524234
Likely Pathogenic Old Model - average_confidence_normal: 0.7245090121652594
Likely Pathogenic Old Model - average_confidence_mutated: 0.7599830850824175
==================================================
likely pathogenic new model stats
Likely Pathogenic New Model - number_of_variants: 1959
Likely Pathogenic New Model - number_of_mutated_protien_seq: 250
Likely Pathogenic New Model - number_of_normal_protien_seq: 1709
Likely Pathogenic New Model - mutated_percentage_to_total: 12.76161306789178
Likely Pathogenic New Model - average_confidence: 0.5439167837161818
Likely Pathogenic New Model - average_confidence_normal: 0.5368088315272089
Likely Pathogenic New Model - average_confidence_mutated: 0.59250674488
==================================================
likely pathogenic newest model stats
Likely Pathogenic Newest Model - number_of_variants: 873
Likely Pathogenic Newest Model - number_of_mutated_protien_seq: 120
Likely Pathogenic Newest Model - number_of_normal_protien_seq: 753
Likely Pathogenic Newest Model - mutated_percentage_to_total: 13.745704467353953
Likely Pathogenic Newest Model - average_confidence: 0.7691624626689577
Likely Pathogenic Newest Model - average_confidence_normal: 0.7651098529349271
Likely Pathogenic Newest Model - average_confidence_mutated: 0.79459258875
==================================================
Likely Pathogenic Model 4 Stats
Model 4 - number_of_variants: 1522
Model 4 - number_of_mutated_protien_seq: 325
Model 4 - number_of_normal_protien_seq: 1197
Model 4 - mutated_percentage_to_total: 21.353482260183966
Model 4 - average_confidence: 0.7171144692509857
Model 4 - average_confidence_normal: 0.7044335796407686
Model 4 - average_confidence_mutated: 0.7638191611384615
==================================================
Likely Pathogenic Model 5 Stats
Model 5 - number_of_variants: 1351
Model 5 - number_of_mutated_protien_seq: 234
Model 5 - number_of_normal_protien_seq: 1117
Model 5 - mutated_percentage_to_total: 17.320503330866025
Model 5 - average_confidence: 0.6932578299777942
Model 5 - average_confidence_normal: 0.6835558406535363
Model 5 - average_confidence_mutated: 0.7395703174786326
==================================================
Likely Pathogenic Model 6 Stats
Model 6 - number_of_variants: 110
Model 6 - number_of_mutated_protien_seq: 30
Model 6 - number_of_normal_protien_seq: 80
Model 6 - mutated_percentage_to_total: 27.27272727272727
Model 6 - average_confidence: 0.38459133963636366
Model 6 - average_confidence_normal: 0.377933813375
Model 6 - average_confidence_mutated: 0.40234474299999995
==================================================
benign old model stats
Benign Old Model - number_of_variants: 4306
Benign Old Model - number_of_mutated_protien_seq: 15
Benign Old Model - number_of_normal_protien_seq: 4291
Benign Old Model - mutated_percentage_to_total: 0.34835113794705064
Benign Old Model - average_confidence: 0.7943513138086391
Benign Old Model - average_confidence_normal: 0.7950128199021207
Benign Old Model - average_confidence_mutated: 0.6051164706666666
==================================================
benign new model stats
Benign New Model - number_of_variants: 4427
Benign New Model - number_of_mutated_protien_seq: 33
Benign New Model - number_of_normal_protien_seq: 4394
Benign New Model - mutated_percentage_to_total: 0.7454257962502824
Benign New Model - average_confidence: 0.6291529043934945
Benign New Model - average_confidence_normal: 0.6301557763222576
Benign New Model - average_confidence_mutated: 0.49561898757575756
==================================================
benign newest model stats
Benign Newest Model - number_of_variants: 3097
Benign Newest Model - number_of_mutated_protien_seq: 7
Benign Newest Model - number_of_normal_protien_seq: 3090
Benign Newest Model - mutated_percentage_to_total: 0.22602518566354535
Benign Newest Model - average_confidence: 0.8043134271197934
Benign Newest Model - average_confidence_normal: 0.8046280603786408
Benign Newest Model - average_confidence_mutated: 0.665425317142857
==================================================
benign model 4 stats
Model 4 - number_of_variants: 3910
Model 4 - number_of_mutated_protien_seq: 18
Model 4 - number_of_normal_protien_seq: 3892
Model 4 - mutated_percentage_to_total: 0.46035805626598464
Model 4 - average_confidence: 0.8208912240204604
Model 4 - average_confidence_normal: 0.8216579678288798
Model 4 - average_confidence_mutated: 0.6551041738888889
==================================================
benign model 5 stats
Model 5 - number_of_variants: 3666
Model 5 - number_of_mutated_protien_seq: 14
Model 5 - number_of_normal_protien_seq: 3652
Model 5 - mutated_percentage_to_total: 0.3818876159301691
Model 5 - average_confidence: 0.7745140485242773
Model 5 - average_confidence_normal: 0.7751521063472071
Model 5 - average_confidence_mutated: 0.6080721078571428
==================================================
benign model 6 stats
Model 6 - number_of_variants: 1606
Model 6 - number_of_mutated_protien_seq: 3
Model 6 - number_of_normal_protien_seq: 1603
Model 6 - mutated_percentage_to_total: 0.18679950186799502
Model 6 - average_confidence: 0.8015402536861768
Model 6 - average_confidence_normal: 0.8021137544603867
Model 6 - average_confidence_mutated: 0.4950996733333333
==================================================
likely benign old model stats
Likely Benign Old Model - number_of_variants: 22185
Likely Benign Old Model - number_of_mutated_protien_seq: 729
Likely Benign Old Model - number_of_normal_protien_seq: 21456
Likely Benign Old Model - mutated_percentage_to_total: 3.286004056795132
Likely Benign Old Model - average_confidence: 0.7865933791877395
Likely Benign Old Model - average_confidence_normal: 0.7868266810887398
Likely Benign Old Model - average_confidence_mutated: 0.7797268145953362
==================================================
likely benign new model stats
Likely Benign New Model - number_of_variants: 22273
Likely Benign New Model - number_of_mutated_protien_seq: 849
Likely Benign New Model - number_of_normal_protien_seq: 21424
Likely Benign New Model - mutated_percentage_to_total: 3.8117900597135543
Likely Benign New Model - average_confidence: 0.5298210714326764
Likely Benign New Model - average_confidence_normal: 0.528394082098581
Likely Benign New Model - average_confidence_mutated: 0.5658302816725559
==================================================
likely benign newest model stats
Likely Benign Newest Model - number_of_variants: 24560
Likely Benign Newest Model - number_of_mutated_protien_seq: 984
Likely Benign Newest Model - number_of_normal_protien_seq: 23576
Likely Benign Newest Model - mutated_percentage_to_total: 4.006514657980456
Likely Benign Newest Model - average_confidence: 0.9027369850207655
Likely Benign Newest Model - average_confidence_normal: 0.9023020224567356
Likely Benign Newest Model - average_confidence_mutated: 0.913158405152439
==================================================
Likely Benign Model 4 Stats
Model 4 - number_of_variants: 14742
Model 4 - number_of_mutated_protien_seq: 608
Model 4 - number_of_normal_protien_seq: 14134
Model 4 - mutated_percentage_to_total: 4.124270790937458
Model 4 - average_confidence: 0.7820728913498847
Model 4 - average_confidence_normal: 0.7820671184448847
Model 4 - average_confidence_mutated: 0.7822070924013158
==================================================
Likely Benign Model 5 Stats
Model 5 - number_of_variants: 22581
Model 5 - number_of_mutated_protien_seq: 838
Model 5 - number_of_normal_protien_seq: 21743
Model 5 - mutated_percentage_to_total: 3.711084540100084
Model 5 - average_confidence: 0.7659100036982418
Model 5 - average_confidence_normal: 0.7652936844464885
Model 5 - average_confidence_mutated: 0.7819012083412887
==================================================
Likely Benign Model 6 Stats
Model 6 - number_of_variants: 26677
Model 6 - number_of_mutated_protien_seq: 1079
Model 6 - number_of_normal_protien_seq: 25598
Model 6 - mutated_percentage_to_total: 4.044682685459384
Model 6 - average_confidence: 0.9271642198605541
Model 6 - average_confidence_normal: 0.9297138085295725
Model 6 - average_confidence_mutated: 0.8666782414087117
==================================================

In [19]:
pathogenic_model_6 = model_6[(model_6['Predicted_Label_Display'] == 'Pathogenic') & (model_6['normal_seq'] == False)]

pathogenic_model_6.head(50)

,snp_id,protein_sequence,variant_type,position,gene,original,mutant,frequency,function_class,Predicted_Label_Original,Prediction_Confidence,Predicted_Label_Display,normal_seq
3063,1162160250,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169470034,SLC19A2,-,CA,CA:0.000002:1:GnomAD_exomes,frameshift_variant;coding_sequence_variant,-2,0.800431,Pathogenic,False
3519,1213206212,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468665,SLC19A2,AT,-,-:0.0000029:4:GnomAD_exomes,frameshift_variant;coding_sequence_variant,-2,0.903238,Pathogenic,False
4960,1379204044,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468243,SLC19A2,A,-,NaN,frameshift_variant;coding_sequence_variant,-2,0.953704,Pathogenic,False
6106,1553213506,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFPAS...,del,169485637,SLC19A2,C,-,-:0.03163:329:GoESP,frameshift_variant;coding_sequence_variant,-2,0.791506,Pathogenic,False
6135,1557889112,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169469971,SLC19A2,G,-,-:0.000003:2:GnomAD_exomes|-:0.000004:1:TOPMED...,frameshift_variant;coding_sequence_variant,-2,0.749593,Pathogenic,False
6773,1657974167,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169465861,SLC19A2,-,A,A:0.000007:1:GnomAD_genomes|A:0.000008:2:TOPME...,frameshift_variant;coding_sequence_variant,-2,0.400826,Pathogenic,False
7026,1658076788,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468143,SLC19A2,C,-,-:0.000004:1:TOPMED|-:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.956557,Pathogenic,False
7027,1658076868,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468145,SLC19A2,-,TGTGTAG,TGTGTAG:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.907396,Pathogenic,False
7086,1658095371,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468752,SLC19A2,A,-,-:0.000008:2:TOPMED|-:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.902086,Pathogenic,False
7090,1658096725,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468795,SLC19A2,A,-,-:0.0000014:2:GnomAD_exomes|-:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.796356,Pathogenic,False
7094,1658097604,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468813,SLC19A2,-,A,AAA:0.:0:ALFA,coding_sequence_variant;frameshift_variant,-2,0.817888,Pathogenic,False
7220,1658132918,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470100,SLC19A2,C,T,T:0.:0:ALFA,coding_sequence_variant;stop_gained,-2,0.838964,Pathogenic,False
7221,1658133007,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470101,SLC19A2,C,T,A:0.000002:1:GnomAD_exomes|T:0.:0:ALFA,coding_sequence_variant;stop_gained;missense_v...,-2,0.856137,Pathogenic,False
8067,1658340278,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477202,SLC19A2,C,A,G:0.0000007:1:GnomAD_exomes|A:0.0000067:1:Gnom...,coding_sequence_variant;intron_variant;missens...,-2,0.741842,Pathogenic,False
8100,1658355778,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477646,SLC19A2,-,C,C:0.000004:1:TOPMED|CCCCC:0.:0:ALFA,coding_sequence_variant;intron_variant;framesh...,-2,0.997826,Pathogenic,False
8106,1658357756,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169477715,SLC19A2,CCAGGT,-,-:0.000007:1:GnomAD_genomes|-:0.000004:1:TOPME...,coding_sequence_variant;intron_variant;inframe...,-2,0.883128,Pathogenic,False
8974,1658538909,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169485565,SLC19A2,C,-,-:0.000007:1:GnomAD_genomes|-:0.000004:1:TOPME...,coding_sequence_variant;frameshift_variant,-2,0.907458,Pathogenic,False
9495,2101773099,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468113,SLC19A2,G,A,T:0.000002:1:GnomAD_exomes,missense_variant;stop_gained;coding_sequence_v...,-2,0.882250,Pathogenic,False
9497,2101773237,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468224,SLC19A2,C,A,A:0.00001:1:TOMMO,stop_gained;coding_sequence_variant,-2,0.965418,Pathogenic,False
9853,2526228997,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169465907,SLC19A2,-,T,T:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.611689,Pathogenic,False
9861,2526229214,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169465965,SLC19A2,C,T,T:0.000002:1:GnomAD_exomes,missense_variant;coding_sequence_variant,-2,0.385787,Pathogenic,False
9966,2526234346,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468152,SLC19A2,CAATTAGAGTGAGCA,CA,-:0.0000043:6:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.944737,Pathogenic,False
10053,2526235999,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468658,SLC19A2,-,A,A:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.966528,Pathogenic,False
10061,2526236130,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468700,SLC19A2,G,-,-:0.00001:1:TOMMO,coding_sequence_variant;frameshift_variant,-2,0.900927,Pathogenic,False
10064,2526236154,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468706,SLC19A2,C,T,T:0.000002:1:GnomAD_exomes,coding_sequence_variant;stop_gained,-2,0.925945,Pathogenic,False
10067,2526236190,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468713,SLC19A2,-,CCATGA,CCATGA:0.0000007:1:GnomAD_exomes,inframe_indel;coding_sequence_variant,-2,0.684471,Pathogenic,False
10072,2526236236,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468728,SLC19A2,-,C,C:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.802500,Pathogenic,False
10074,2526236253,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468730,SLC19A2,-,TGCAGCA,TGCAGCA:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.946082,Pathogenic,False
10075,2526236267,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169468732,SLC19A2,-,CAGGAGAG,CAGGAGAG:0.0000007:1:GnomAD_exomes,inframe_indel;coding_sequence_variant;stop_gained,-2,0.974559,Pathogenic,False
10079,2526236348,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468759,SLC19A2,A,-,-:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.881777,Pathogenic,False
10083,2526236371,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468770,SLC19A2,A,-,-:0.0000007:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.898020,Pathogenic,False
10084,2526236447,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468791,SLC19A2,G,T,T:0.000002:1:GnomAD_exomes,coding_sequence_variant;stop_gained,-2,0.850435,Pathogenic,False
10085,2526236453,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169468791,SLC19A2,GACCAG,G,-:0.000002:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.917098,Pathogenic,False
10206,2526239699,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169469990,SLC19A2,CCA,-,-:0.0000007:1:GnomAD_exomes,coding_sequence_variant;inframe_deletion,-2,0.420193,Pathogenic,False
10223,2526240071,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169470079,SLC19A2,AG,-,-:0.000002:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.950572,Pathogenic,False
10224,2526240078,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169470083,SLC19A2,A,-,-:0.000001:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.964400,Pathogenic,False
10401,2526255842,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477167,SLC19A2,G,-,-:0.0000014:2:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.890743,Pathogenic,False
10424,2526256167,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169477297,SLC19A2,-,T,T:0.000002:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.881720,Pathogenic,False
10428,2526256643,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477335,SLC19A2,AGGTAAAAACCAGG,AGG,-:0.0000007:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.920184,Pathogenic,False
10439,2526256896,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477403,SLC19A2,GCGACCAGCCTGCCACTG,G,-:0.0000014:2:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.878598,Pathogenic,False
10440,2526256902,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169477403,SLC19A2,-,A,A:0.0000007:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.896127,Pathogenic,False
10441,2526256925,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169477406,SLC19A2,-,T,T:0.000001:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.877823,Pathogenic,False
10442,2526256938,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477408,SLC19A2,C,T,T:0.000001:1:GnomAD_exomes,intron_variant;coding_sequence_variant;stop_ga...,-2,0.911753,Pathogenic,False
10458,2526257190,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,ins,169477503,SLC19A2,-,T,T:0.0000007:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.925237,Pathogenic,False
10459,2526257209,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169477505,SLC19A2,TGCC,-,-:0.0000007:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.962031,Pathogenic,False
10461,2526257374,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477552,SLC19A2,G,A,A:0.00001:1:TOMMO,missense_variant;intron_variant;coding_sequenc...,-2,0.417783,Pathogenic,False
10482,2526257789,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477684,SLC19A2,T,G,G:0.00001:1:TOMMO,missense_variant;intron_variant;coding_sequenc...,-2,0.417498,Pathogenic,False
10486,2526257854,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169477696,SLC19A2,A,-,-:0.000001:1:GnomAD_exomes,intron_variant;coding_sequence_variant;framesh...,-2,0.954448,Pathogenic,False
10721,2526274073,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,delins,169485599,SLC19A2,-,T,T:0.0000007:1:GnomAD_exomes,coding_sequence_variant;stop_gained,-2,0.935680,Pathogenic,False
10746,2526275035,MDVPGPVSRRAAAAAPLCSCGPLGSVANAGSCRPRCSAPTASSPAS...,delins,169485721,SLC19A2,C,-,-:0.0000008:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.954108,Pathogenic,False

In [20]:
likely_pathogenic_model_6 = model_6[(model_6['Predicted_Label_Display'] == 'Likely Pathogenic') & (model_6['normal_seq'] == False)]

likely_pathogenic_model_6.head(50)

,snp_id,protein_sequence,variant_type,position,gene,original,mutant,frequency,function_class,Predicted_Label_Original,Prediction_Confidence,Predicted_Label_Display,normal_seq
3904,1257494661,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477571,SLC19A2,A,T,T:0.000002:1:GnomAD_exomes,missense_variant;coding_sequence_variant;intro...,-1,0.404974,Likely Pathogenic,False
4030,1271391695,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169465851,SLC19A2,A,G,G:0.0000086:12:GnomAD_exomes|G:0.0000038:1:TOP...,terminator_codon_variant;stop_lost,-1,0.444810,Likely Pathogenic,False
10218,2526239969,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470051,SLC19A2,A,T,NaN,missense_variant;coding_sequence_variant,-1,0.352211,Likely Pathogenic,False
10476,2526257694,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477666,SLC19A2,G,A,A:0.000001:1:GnomAD_exomes,missense_variant;intron_variant;coding_sequenc...,-1,0.389137,Likely Pathogenic,False
11541,747950227,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470065,SLC19A2,A,G,G:0.000008:1:ExAC|G:0.000003:2:GnomAD_exomes,coding_sequence_variant;missense_variant,-1,0.342136,Likely Pathogenic,False
11598,752357863,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477697,SLC19A2,A,G,G:0.000017:2:ExAC|G:0.000013:8:GnomAD_exomes|G...,missense_variant;coding_sequence_variant;intro...,-1,0.383774,Likely Pathogenic,False
11918,776903674,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477532,SLC19A2,A,T,T:0.000008:1:ExAC|T:0.000002:1:GnomAD_exomes|T...,coding_sequence_variant;intron_variant;missens...,-1,0.346828,Likely Pathogenic,False
12012,79619136,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477559,SLC19A2,T,G,G:0.016531:1936:ExAC|G:0.008188:15:Korea1K,intron_variant;coding_sequence_variant;missens...,-1,0.399144,Likely Pathogenic,False
13624,1034063734,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227695914,SLC19A3,A,G,NaN,coding_sequence_variant;missense_variant,-1,0.414397,Likely Pathogenic,False
14265,1164678779,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227699374,SLC19A3,C,A,G:0.000013:2:GnomAD_genomes|G:0.:0:ALFA,coding_sequence_variant;missense_variant,-1,0.347180,Likely Pathogenic,False
15401,1239156852,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,delins,227687505,SLC19A3,G,-,-:0.000007:1:GnomAD_genomes|-:0.000004:1:TOPME...,coding_sequence_variant;frameshift_variant,-1,0.418578,Likely Pathogenic,False
16585,1321806557,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227699363,SLC19A3,C,G,T:0.000007:1:GnomAD_genomes|T:0.000019:5:TOPME...,coding_sequence_variant;missense_variant,-1,0.391412,Likely Pathogenic,False
17233,1366317721,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227699351,SLC19A3,C,T,T:0.0000064:9:GnomAD_exomes|T:0.0000067:1:Gnom...,missense_variant;coding_sequence_variant,-1,0.456520,Likely Pathogenic,False
17657,1395917397,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227696040,SLC19A3,A,C,C:0.:0:ALFA,missense_variant;coding_sequence_variant,-1,0.424041,Likely Pathogenic,False
19055,1485371682,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227699255,SLC19A3,C,T,T:0.000007:1:GnomAD_genomes|T:0.:0:ALFA,coding_sequence_variant;missense_variant,-1,0.402598,Likely Pathogenic,False
19101,1487627565,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227699065,SLC19A3,A,C,G:0.000001:1:GnomAD_exomes|G:0.:0:ALFA,coding_sequence_variant;missense_variant;stop_...,-1,0.387775,Likely Pathogenic,False
21758,1695566341,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227699143,SLC19A3,G,A,A:0.0000014:2:GnomAD_exomes|A:0.0000258:2:TOMMO,coding_sequence_variant;missense_variant,-1,0.415833,Likely Pathogenic,False
21774,1695589066,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227699491,SLC19A3,T,C,C:0.00005:1:ALFA,coding_sequence_variant;missense_variant,-1,0.419081,Likely Pathogenic,False
26013,2470568125,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227696006,SLC19A3,A,G,G:0.000001:1:GnomAD_exomes,coding_sequence_variant;missense_variant,-1,0.447528,Likely Pathogenic,False
26227,2470574537,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227699353,SLC19A3,A,G,G:0.000005:7:GnomAD_exomes,coding_sequence_variant;missense_variant,-1,0.418126,Likely Pathogenic,False
26252,2470575173,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227699512,SLC19A3,A,G,G:0.000003:2:GnomAD_exomes,coding_sequence_variant;missense_variant,-1,0.399310,Likely Pathogenic,False
26517,2470580944,MDCYRTSLSSSWIYPTVILCLFLGFFSMMRPSEPFLIPYLSGPDKN...,delins,227702253,SLC19A3,-,TAA,AAT:0.:0:GnomAD_exomes,coding_sequence_variant;inframe_insertion;5_pr...,-1,0.458958,Likely Pathogenic,False
27410,370463398,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227699455,SLC19A3,C,T,T:0.000008:1:ExAC|T:0.000002:1:GnomAD_exomes|T...,missense_variant;coding_sequence_variant,-1,0.347652,Likely Pathogenic,False
28703,752393233,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227688209,SLC19A3,A,T,G:0.000025:3:ExAC|G:0.000007:1:GnomAD_genomes|...,missense_variant;coding_sequence_variant,-1,0.362421,Likely Pathogenic,False
28763,755184234,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227699366,SLC19A3,T,G,C:0.0000082:1:ExAC|C:0.000005:7:GnomAD_exomes|...,missense_variant;coding_sequence_variant,-1,0.392393,Likely Pathogenic,False
28764,755201449,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,delins,227699509,SLC19A3,-,GCA,GCA:0.0000082:1:ExAC|GCA:0.0000014:2:GnomAD_ex...,inframe_insertion;coding_sequence_variant,-1,0.478818,Likely Pathogenic,False
28865,759172102,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227699338,SLC19A3,T,G,G:0.000008:1:ExAC,coding_sequence_variant;missense_variant,-1,0.439588,Likely Pathogenic,False
28921,761691445,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227696058,SLC19A3,C,T,G:0.000008:1:ExAC|T:0.000039:3:TOMMO,coding_sequence_variant;missense_variant,-1,0.430897,Likely Pathogenic,False
29146,773702095,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227688296,SLC19A3,G,A,A:0.000008:1:ExAC|A:0.000002:1:GnomAD_exomes,missense_variant;coding_sequence_variant,-1,0.368443,Likely Pathogenic,False
29458,887859933,MDCYRTSLSSSWIYPTVILCLFGFFSMMRPSEPFLIPYLSGPDKNL...,snv,227695898,SLC19A3,G,T,T:0.000002:1:GnomAD_exomes,coding_sequence_variant;missense_variant,-1,0.385776,Likely Pathogenic,False

In [21]:
model_6_not_normal.head(50)

NameError: name 'model_6_not_normal' is not defined

In [22]:
model_6_not_normal = model_6[model_6['normal_seq'] == False]
model_6_not_normal = model_6_not_normal[model_6_not_normal['gene'] == "SLC19A2"]

print("Available rows per label:")
for lbl in ["Pathogenic", "Likely Pathogenic", "Benign", "Likely Benign"]:
    count = (model_6_not_normal['Predicted_Label_Display'] == lbl).sum()
    print(f"{lbl}: {count} rows")

Available rows per label:
Pathogenic: 66 rows
Likely Pathogenic: 8 rows
Benign: 3 rows
Likely Benign: 613 rows

In [23]:
model_6_not_normal = model_6[model_6['normal_seq'] == False]

model_6_not_normal = model_6_not_normal[model_6_not_normal['gene'] == "SLC19A2"]

seed = 65

desired_counts = {
    "Pathogenic": 3,
    "Likely Pathogenic": 2,
    "Benign": 3,
    "Likely Benign": 2
}
parts = []

for lbl, cnt in desired_counts.items():
    pool = model_6_not_normal[model_6_not_normal['Predicted_Label_Display'] == lbl]
    picked = pool.sample(n=cnt, random_state=seed)  # same seed for every label
    parts.append(picked)

# Deterministic overall ordering (optional shuffle; still reproducible with seed)
selected = pd.concat(parts)
selected = selected.sample(frac=1, random_state=seed).copy()  # remove this line if you prefer grouped by label

# Inspect
print(selected['Predicted_Label_Display'].value_counts())
print(model_6.loc[selected.index, 'normal_seq'].value_counts())

Predicted_Label_Display
Pathogenic           3
Benign               3
Likely Pathogenic    2
Likely Benign        2
Name: count, dtype: int64
normal_seq
False    10
Name: count, dtype: int64

In [24]:
selected

,snp_id,protein_sequence,variant_type,position,gene,original,mutant,frequency,function_class,Predicted_Label_Original,Prediction_Confidence,Predicted_Label_Display,normal_seq
10476,2526257694,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477666,SLC19A2,G,A,A:0.000001:1:GnomAD_exomes,missense_variant;intron_variant;coding_sequenc...,-1,0.389137,Likely Pathogenic,False
8067,1658340278,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477202,SLC19A2,C,A,G:0.0000007:1:GnomAD_exomes|A:0.0000067:1:Gnom...,coding_sequence_variant;intron_variant;missens...,-2,0.741842,Pathogenic,False
11541,747950227,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470065,SLC19A2,A,G,G:0.000008:1:ExAC|G:0.000003:2:GnomAD_exomes,coding_sequence_variant;missense_variant,-1,0.342136,Likely Pathogenic,False
4278,1296969176,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468716,SLC19A2,C,A,T:0.0000029:4:GnomAD_exomes|T:0.0000067:1:Gnom...,coding_sequence_variant;missense_variant,2,0.670316,Benign,False
11849,772048171,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468699,SLC19A2,A,-,-:0.0000247:3:ExAC|-:0.:0:GnomAD_exomes,frameshift_variant;coding_sequence_variant,-2,0.921596,Pathogenic,False
5282,1409662486,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169485603,SLC19A2,G,T,C:0.000004:1:TOPMED|C:0.:0:ALFA,coding_sequence_variant;missense_variant,2,0.500523,Benign,False
10224,2526240078,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169470083,SLC19A2,A,-,-:0.000001:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.964400,Pathogenic,False
12722,957742567,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470117,SLC19A2,G,A,A:0.00001:6:GnomAD_exomes|A:0.000007:1:GnomAD_...,coding_sequence_variant;missense_variant,1,0.938630,Likely Benign,False
3746,1237709955,MDVPGPVSRLAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169485738,SLC19A2,C,A,A:0.0000023:3:GnomAD_exomes,coding_sequence_variant;missense_variant,1,0.974586,Likely Benign,False
3185,1176088261,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169485609,SLC19A2,A,G,G:0.000223:1:Estonian|G:0.000007:1:GnomAD_geno...,coding_sequence_variant;missense_variant,2,0.314461,Benign,False

In [25]:
selected.to_csv("results/model_6_selected_slc19a2.csv", index=False)

In [26]:
path_1 = "Both Genes/final_dataset/final_dataset_SLC19A2_model_5.pkl"
path_2 = "Both Genes/final_dataset/final_dataset_SLC19A3_model_5.pkl"

reference_1 = pd.read_pickle(path_1)
reference_2 = pd.read_pickle(path_2)

merged = pd.concat([reference_1, reference_2], axis=0)

merged

,#chr,pos,variation,variant_type,snp_id,clinical_significance,validation_status,function_class,gene,frequency,...,Siberian_is_mentioned,Qatari_freq,Qatari_is_mentioned,Avg_Frequency,Max_Frequency,Min_Frequency,Total_Studies,by-frequency,by-alfa,by-cluster
0,1,169476354,T>C,snv,1000230073,NaN,by-frequency;by-alfa;by-cluster,intron_variant,SLC19A2,C:0.000013:2:GnomAD_genomes|C:0.000008:2:TOPME...,...,0,0.000000,0,0.000031,0.000071,0.000008,3,1,1,1
1,1,169476354,T>C,snv,1000230073,normal,by-frequency;by-alfa;by-cluster,intron_variant,SLC19A2,C:0.000013:2:GnomAD_genomes|C:0.000008:2:TOPME...,...,0,0.000000,0,0.082630,0.185311,0.005581,5,1,1,1
2,1,169475878,T>C,snv,1000304891,normal,by-frequency;by-alfa;by-cluster,intron_variant,SLC19A2,C:0.000007:1:GnomAD_genomes|C:0.000008:2:TOPME...,...,0,0.000000,0,0.056416,0.175923,0.004349,11,1,1,1
3,1,169475878,T>C,snv,1000304891,NaN,by-frequency;by-alfa;by-cluster,intron_variant,SLC19A2,C:0.000007:1:GnomAD_genomes|C:0.000008:2:TOPME...,...,0,0.000000,0,0.000007,0.000008,0.000007,2,1,1,1
4,1,169483460,T>C,snv,1000361639,normal,by-frequency;by-alfa,intron_variant,SLC19A2,C:0.:0:ALFA,...,0,0.100872,1,0.058910,0.139787,0.000490,14,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38887,2,227717362,"G>A,C",snv,999920369,NaN,by-frequency;by-alfa;by-cluster,intron_variant;genic_upstream_transcript_variant,SLC19A3,A:0.000007:1:GnomAD_genomes|A:0.000004:1:TOPME...,...,0,0.000000,0,0.000000,0.000000,0.000000,0,1,1,1
38888,2,227713769,A>G,snv,999966616,normal,by-frequency;by-alfa;by-cluster,intron_variant;genic_upstream_transcript_variant,SLC19A3,G:0.00002:3:GnomAD_genomes|A:0.5:2:SGDP_PRJ|G:...,...,0,0.000000,0,0.078980,0.221114,0.000119,11,1,1,1
38889,2,227713769,A>G,snv,999966616,NaN,by-frequency;by-alfa;by-cluster,intron_variant;genic_upstream_transcript_variant,SLC19A3,G:0.00002:3:GnomAD_genomes|A:0.5:2:SGDP_PRJ|G:...,...,0,0.000000,0,0.000022,0.000023,0.000020,2,1,1,1
38890,2,227690580,G>A,snv,999983906,NaN,by-frequency;by-alfa;by-cluster,intron_variant,SLC19A3,A:0.000156:1:1000Genomes_30X|A:0.000081:12:Gno...,...,0,0.000000,0,0.000418,0.001369,0.000081,6,1,1,1
38891,2,227690580,G>A,snv,999983906,normal,by-frequency;by-alfa;by-cluster,intron_variant,SLC19A3,A:0.000156:1:1000Genomes_30X|A:0.000081:12:Gno...,...,0,0.000000,0,0.039621,0.091251,0.014138,8,1,1,1

In [27]:
print(merged.columns.tolist())

['#chr', 'pos', 'variation', 'variant_type', 'snp_id', 'clinical_significance', 'validation_status', 'function_class', 'gene', 'frequency', 'original', 'mutant', 'generated_dna', 'generated_mRNA', 'protein_sequence', 'MGP_freq', 'MGP_is_mentioned', 'HGDP_Stanford_freq', 'HGDP_Stanford_is_mentioned', 'FINRISK_freq', 'FINRISK_is_mentioned', 'Chileans_freq', 'Chileans_is_mentioned', 'GENOME_DK_freq', 'GENOME_DK_is_mentioned', 'PharmGKB_freq', 'PharmGKB_is_mentioned', 'GnomAD_exomes_freq', 'GnomAD_exomes_is_mentioned', 'SGDP_PRJ_freq', 'SGDP_PRJ_is_mentioned', 'ExAC_freq', 'ExAC_is_mentioned', 'PAGE_STUDY_freq', 'PAGE_STUDY_is_mentioned', 'Korea1K_freq', 'Korea1K_is_mentioned', 'Estonian_freq', 'Estonian_is_mentioned', 'ALSPAC_freq', 'ALSPAC_is_mentioned', 'Korea4K_freq', 'Korea4K_is_mentioned', 'KOREAN_freq', 'KOREAN_is_mentioned', 'GENOGRAPHIC_freq', 'GENOGRAPHIC_is_mentioned', 'Daghestan_freq', 'Daghestan_is_mentioned', 'GoNL_freq', 'GoNL_is_mentioned', 'TOMMO_freq', 'TOMMO_is_mentioned', '1000Genomes_30X_freq', '1000Genomes_30X_is_mentioned', 'HapMap_freq', 'HapMap_is_mentioned', '1000Genomes_freq', '1000Genomes_is_mentioned', 'TWINSUK_freq', 'TWINSUK_is_mentioned', 'NorthernSweden_freq', 'NorthernSweden_is_mentioned', 'PRJEB36033_freq', 'PRJEB36033_is_mentioned', 'GoESP_freq', 'GoESP_is_mentioned', 'Vietnamese_freq', 'Vietnamese_is_mentioned', 'TOPMED_freq', 'TOPMED_is_mentioned', 'PRJEB37584_freq', 'PRJEB37584_is_mentioned', 'ALFA_freq', 'ALFA_is_mentioned', 'GnomAD_genomes_freq', 'GnomAD_genomes_is_mentioned', 'Siberian_freq', 'Siberian_is_mentioned', 'Qatari_freq', 'Qatari_is_mentioned', 'Avg_Frequency', 'Max_Frequency', 'Min_Frequency', 'Total_Studies', 'by-frequency', 'by-alfa', 'by-cluster']

In [28]:
# Ensure both columns are of the same type (convert to string for both snp_id and mutant)
selected['snp_id'] = selected['snp_id'].astype(str)
selected['mutant'] = selected['mutant'].astype(str)
merged['snp_id'] = merged['snp_id'].astype(str)
merged['mutant'] = merged['mutant'].astype(str)

# Perform the merge on both snp_id and mutant
selected = selected.merge(
    merged[['snp_id', 'mutant', 'generated_dna']],
    on=['snp_id', 'mutant'],
    how='left'
).rename(columns={'generated_dna': 'dna_sequence'})

selected

,snp_id,protein_sequence,variant_type,position,gene,original,mutant,frequency,function_class,Predicted_Label_Original,Prediction_Confidence,Predicted_Label_Display,normal_seq,dna_sequence
0,2526257694,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477666,SLC19A2,G,A,A:0.000001:1:GnomAD_exomes,missense_variant;intron_variant;coding_sequenc...,-1,0.389137,Likely Pathogenic,False,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...
1,1658340278,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169477202,SLC19A2,C,A,G:0.0000007:1:GnomAD_exomes|A:0.0000067:1:Gnom...,coding_sequence_variant;intron_variant;missens...,-2,0.741842,Pathogenic,False,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...
2,747950227,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470065,SLC19A2,A,G,G:0.000008:1:ExAC|G:0.000003:2:GnomAD_exomes,coding_sequence_variant;missense_variant,-1,0.342136,Likely Pathogenic,False,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...
3,1296969176,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169468716,SLC19A2,C,A,T:0.0000029:4:GnomAD_exomes|T:0.0000067:1:Gnom...,coding_sequence_variant;missense_variant,2,0.670316,Benign,False,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...
4,772048171,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169468699,SLC19A2,A,-,-:0.0000247:3:ExAC|-:0.:0:GnomAD_exomes,frameshift_variant;coding_sequence_variant,-2,0.921596,Pathogenic,False,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...
5,1409662486,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169485603,SLC19A2,G,T,C:0.000004:1:TOPMED|C:0.:0:ALFA,coding_sequence_variant;missense_variant,2,0.500523,Benign,False,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...
6,2526240078,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,del,169470083,SLC19A2,A,-,-:0.000001:1:GnomAD_exomes,coding_sequence_variant;frameshift_variant,-2,0.964400,Pathogenic,False,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...
7,957742567,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169470117,SLC19A2,G,A,A:0.00001:6:GnomAD_exomes|A:0.000007:1:GnomAD_...,coding_sequence_variant;missense_variant,1,0.938630,Likely Benign,False,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...
8,1237709955,MDVPGPVSRLAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169485738,SLC19A2,C,A,A:0.0000023:3:GnomAD_exomes,coding_sequence_variant;missense_variant,1,0.974586,Likely Benign,False,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...
9,1176088261,MDVPGPVSRRAAAAAATVLLRTARVRRECWFLPTALLCAYGFFASL...,snv,169485609,SLC19A2,A,G,G:0.000223:1:Estonian|G:0.000007:1:GnomAD_geno...,coding_sequence_variant;missense_variant,2,0.314461,Benign,False,ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTC...

In [29]:
selected.to_csv("results/selected_variants_slca19a2.csv", index=False)

In [30]:
merged

,#chr,pos,variation,variant_type,snp_id,clinical_significance,validation_status,function_class,gene,frequency,...,Siberian_is_mentioned,Qatari_freq,Qatari_is_mentioned,Avg_Frequency,Max_Frequency,Min_Frequency,Total_Studies,by-frequency,by-alfa,by-cluster
0,1,169476354,T>C,snv,1000230073,NaN,by-frequency;by-alfa;by-cluster,intron_variant,SLC19A2,C:0.000013:2:GnomAD_genomes|C:0.000008:2:TOPME...,...,0,0.000000,0,0.000031,0.000071,0.000008,3,1,1,1
1,1,169476354,T>C,snv,1000230073,normal,by-frequency;by-alfa;by-cluster,intron_variant,SLC19A2,C:0.000013:2:GnomAD_genomes|C:0.000008:2:TOPME...,...,0,0.000000,0,0.082630,0.185311,0.005581,5,1,1,1
2,1,169475878,T>C,snv,1000304891,normal,by-frequency;by-alfa;by-cluster,intron_variant,SLC19A2,C:0.000007:1:GnomAD_genomes|C:0.000008:2:TOPME...,...,0,0.000000,0,0.056416,0.175923,0.004349,11,1,1,1
3,1,169475878,T>C,snv,1000304891,NaN,by-frequency;by-alfa;by-cluster,intron_variant,SLC19A2,C:0.000007:1:GnomAD_genomes|C:0.000008:2:TOPME...,...,0,0.000000,0,0.000007,0.000008,0.000007,2,1,1,1
4,1,169483460,T>C,snv,1000361639,normal,by-frequency;by-alfa,intron_variant,SLC19A2,C:0.:0:ALFA,...,0,0.100872,1,0.058910,0.139787,0.000490,14,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38887,2,227717362,"G>A,C",snv,999920369,NaN,by-frequency;by-alfa;by-cluster,intron_variant;genic_upstream_transcript_variant,SLC19A3,A:0.000007:1:GnomAD_genomes|A:0.000004:1:TOPME...,...,0,0.000000,0,0.000000,0.000000,0.000000,0,1,1,1
38888,2,227713769,A>G,snv,999966616,normal,by-frequency;by-alfa;by-cluster,intron_variant;genic_upstream_transcript_variant,SLC19A3,G:0.00002:3:GnomAD_genomes|A:0.5:2:SGDP_PRJ|G:...,...,0,0.000000,0,0.078980,0.221114,0.000119,11,1,1,1
38889,2,227713769,A>G,snv,999966616,NaN,by-frequency;by-alfa;by-cluster,intron_variant;genic_upstream_transcript_variant,SLC19A3,G:0.00002:3:GnomAD_genomes|A:0.5:2:SGDP_PRJ|G:...,...,0,0.000000,0,0.000022,0.000023,0.000020,2,1,1,1
38890,2,227690580,G>A,snv,999983906,NaN,by-frequency;by-alfa;by-cluster,intron_variant,SLC19A3,A:0.000156:1:1000Genomes_30X|A:0.000081:12:Gno...,...,0,0.000000,0,0.000418,0.001369,0.000081,6,1,1,1
38891,2,227690580,G>A,snv,999983906,normal,by-frequency;by-alfa;by-cluster,intron_variant,SLC19A3,A:0.000156:1:1000Genomes_30X|A:0.000081:12:Gno...,...,0,0.000000,0,0.039621,0.091251,0.014138,8,1,1,1

In [31]:
normal_mrna_slc19a2 = merged.loc[(merged["clinical_significance"] == 'normal'), "generated_mRNA"].iloc[0]

normal_mrna_slc19a2

'AGAGGCGUCUGUAGGGUAAAGCUGGGGGUUCUGUAGCCGGAGGCGGCGGCGAGUCCAGAACGUCCUGGCCUUACAGGGAGAAGGCGUCACUCGCGGUUACAAGUGCCUGACCCUCACUCCAGUUGGCGGAGGAGGAGAAGGAAGGGGCCGGGCCGGGUCCCCUCCCCUCGCGCCCCGGAUGGAUGUGCCCGGCCCGGUGUCUCGGCGGGCGGCGGCGGCGGCGGCCACUGUGCUCCUGCGGACCGCUCGGGUCCGUCGCGAAUGCUGGUUCUUGCCGACCGCGCUGCUCUGCGCCUACGGCUUCUUCGCCAGCCUCAGGCCGUCCGAGCCCUUCCUGACCCCGUACCUGCUGGGGCCGGACAAGAACCUGACCGAGAGGGAGGUCUUCAAUGAAAUUUAUCCAGUAUGGACUUACUCUUACCUGGUGCUACUGUUUCCUGUGUUCCUUGCCACAGACUACCUCCGUUAUAAACCUGUUGUUCUACUGCAGGGGCUCAGCCUUAUUGUUACAUGGUUUAUGCUGCUCUAUGCCCAGGGACUGCUGGCCAUUCAAUUUCUAGAAUUUUUUUAUGGCAUCGCCACAGCCACUGAAAUUGCCUAUUACUCUUAUAUCUACAGUGUGGUGGACCUGGGCAUGUACCAGAAAGUCACAAGUUACUGUCGAAGUGCCACUUUGGUGGGCUUUACAGUGGGCUCUGUCCUAGGGCAAAUCCUUGUCUCAGUGGCAGGCUGGUCGCUGUUCAGCCUGAAUGUCAUCUCUCUUACCUGUGUUUCAGUGGCUUUUGCUGUGGCCUGGUUUUUACCUAUGCCACAGAAGAGCCUCUUCUUUCACCACAUUCCUUCUACCUGCCAGAGAGUGAAUGGCAUCAAGGUACAAAAUGGUGGCAUUGUUACUGACACCCCAGCUUCUAACCACCUUCCUGGCUGGGAGGACAUUGAGUCAAAAAUCCCUCUAAAUAUGGAGGAGCCUCCCGUGGAGGAACCGGAACCCAAGCCAGACCGUCUCCUUGUAUUGAAAGUACUAUGGAAUGAUUUCCUGAUGUGCUACUCCUCUCGCCCUCUUCUCUGCUGGUCUGUGUGGUGGGCCCUCUCUACCUGUGGCUAUUUUCAAGUUGUGAACUACACACAGGGCCUGUGGGAGAAAGUGAUGCCUUCUCGCUAUGCUGCUAUCUAUAAUGGUGGCGUGGAGGCCGUUUCAACCUUACUGGGUGCUGUUGCUGUGUUUGCAGUUGGUUAUAUAAAAAUAUCCUGGUCAACUUGGGGAGAAAUGACAUUAUCUCUCUUUUCUCUCCUGAUUGCUGCUGCAGUGUAUAUCAUGGACACUGUGGGUAACAUUUGGGUGUGCUAUGCAUCCUAUGUUGUCUUCAGAAUCAUCUACAUGUUACUCAUCACGAUAGCAACUUUUCAAAUUGCUGCAAACCUCAGCAUGGAACGCUAUGCCCUAGUAUUUGGUGUAAAUACCUUCAUUGCCCUGGCACUGCAGACGCUGCUCACUCUAAUUGUGGUAGAUGCCAGUGGCCUUGGAUUAGAAAUUACCACUCAGUUUUUGAUCUAUGCCAGUUAUUUUGCACUCAUCGCUGUGGUUUUCCUGGCCAGUGGUGCAGUCAGUGUUAUGAAGAAAUGUAGAAAGCUGGAAGAUCCACAAUCAAGUUCUCAAGUAACCACUUCAUAAUAUACUGCUGAAGGGCUUCUUCUUAUAGCAAGAACUCUGCACAGCAACUGCCUGGAUGUGUUUGAUUUUUUAAAGCGUAGACAUAUAUUUAUGAAUGUGCAUUUCUUGACUUCACAGCAGCCACUUGACUAAUACCUUGUGUUCCGGGAAUAACAUGAUACUAUUCAGAGGAGCCAGAAGUAAAGUUUAUUUCAUGGAUUAUUUAUGAGAGCUAAUUUAAGGAUGACUUUUUUUCUGAUUCAAAAGUGAACUUGAUUUUAAAAACCAGUCAAGAGCAAUCAAAGCAGCACAUGGUGUUGUAUACUUCAUUAGCAAGUGAGUUUGGUGUUUUAUAGGUCACAUAUGUCUGUAUCUACUUAGCCAGAUGCUUGGCCUGGUGGGACCAGGGCUCCACAGAGGCCACAAAAUGUUGCAAGUCAUGAUGGAUGGAAAUAUGUUCUAACAGCAUCUGCCUCUAUUCAAUUUAAUUCUUAUUUCUGUGUUACUCAUGUACAUUGGUCUUUCUACAUAGUUAUUCUAUCACUGGCAAUAUUUGUUCUGGUUUAGUGUUCUGUAUUUUAAGGUGUACGUAUCAUUUCUAAUUUUAAGUUAUUUUAAAAAAAUUCAUCAUAUGAAUGUUCUUGGUUCCCAUUGUGACGAUUAUUUAUUUCUGUAAAAUUUGUUUAGAAGUACGUUUUUGCAUUAUUCAUAUGCUUCCCAGAGAAGCUCAUUUAGUUAGAAAAUAAGGCAAGUUUUGAAGCCUGCUAAAUGAAGAGACUUAAGAAAGCUUAAGGUACGCUUGCUUGUCUUUAAAUCUUCAAUAUGAAGGACUAUUAAUUCCAAGAUUAAAAGUUCAUAUAUAGGCUAAAGAUGUAACUAGGCCAUUUGUAUUUGUAUUCCCUUUUAUUUCCAAAAUAAAAUGAAAAAUCUUUUUUUAAUAAUUUCAUCCCUAUUUAUAGUUUUUAUAUUAAUUUGUUUUUCUUAUCCAAGUAAAGAUGUCAAUAGGAAUUGCAUUAGUCCAAGGCCUUUUUCAUAAACUGAGCCUCUUUUCAAUUAUUUCAAUGGGACAGGAACUAGGAUAGAUGUGAUUCCUGCAUUUUUUUACCUUAAAUCUGCCUUUGUUUCUAAAGGUAGAUCAUCUUGAAUAUUUGCUUAAAAUUGCUAGUGAUUUCAUUACCAAGUUACUUGAAAAAAUGUUCUAUAUGCAUUUAAUUCUGAAAUCAGUCUACCAAGGGGCUGCUAGUAUAUGUCAGACAUGAAAACUAUUUUAAAGCUGACUUUGUUGCCUUAUCUUGAAAAGAAUCUAGAUAGGUGCUUUUAACUGGGGUAUUAACUUUUUUAGAAUGACACAGCUGAACAGUGUUAAUAAUAGUGUGUCAAGAUUGCAAAGUCGACAUACUCAUUUGGUUUAAGCAGGAAUCCUAGAAGCAAAUGGAUGGGGAUAAGAAUAGGUCAUUUUCUAUUCACCAUCCUUUACUAUUAAGGGAAAGGAAAAGAACACUAGCUAAGGAAGGGAAAGGGAAGUGAUAUCAUAAAAGUAGCAACCUUCAUUUUACAUUCUGUCUGUUUUUCUUUUUUUGCUUUGUUUUGUUUGUGCUAAUUUGGGAAUUGUGUACUCCGAAACAAGUAGAAAAGUGCUGUUUGAGGGAUUUUAUUAAAUCUUUUUUUAAUGGAAUGUGGUACAAAUUGUUCAUGUUACCAAAGCAAUAUUUCCCUGGAAUUUAAUUCAAAGUUUGUGGCAUACAACCUGAGCCUUUUCUUAUAUAAGACAAGAAUAUGUUCACAUCUUGGUAUGUGGCCAUAUUUAUAGAAUGCUGAACUCAAUGUGCAAGUUGUACUGUAUGCAGUUUUGUAAAUAAGUGAAAAUAAUUUGUUGUACUUUUUAUUCAAUUCUGUAUAGAUUAUAAAAUUAUUUUUAUUAAAUAAAUAUUUUACAGUAUAUUUUCUCUUUUUAAUCAAAA'

In [32]:
mrna = merged.loc[(merged["snp_id"] == '2526240078') & (merged["mutant"] == '-'), "generated_mRNA"].iloc[0]

In [33]:
print(mrna)

AGAGGCGUCUGUAGGGUAAAGCUGGGGGUUCUGUAGCCGGAGGCGGCGGCGAGUCCAGAACGUCCUGGCCUUACAGGGAGAAGGCGUCACUCGCGGUUACAAGUGCCUGACCCUCACUCCAGUUGGCGGAGGAGGAGAAGGAAGGGGCCGGGCCGGGUCCCCUCCCCUCGCGCCCCGGAUGGAUGUGCCCGGCCCGGUGUCUCGGCGGGCGGCGGCGGCGGCGGCCACUGUGCUCCUGCGGACCGCUCGGGUCCGUCGCGAAUGCUGGUUCUUGCCGACCGCGCUGCUCUGCGCCUACGGCUUCUUCGCCAGCCUCAGGCCGUCCGAGCCCUUCCUGACCCCGUACCUGCUGGGGCCGGACAAGAACCUGACCGAGAGGGAGGUCUUCAAUGAAAUUUAUCCAGUAUGGACUUACUCUUACCUGGUGCUACUGUUUCCUGUGUUCCUUGCCACAGACUACCUCCGUUAUAAACCUGUUGUUCUACUGCAGGGGCUCAGCCUUAUUGUUACAUGGUUUAUGCUGCUCUAUGCCCAGGGACUGCUGGCCAUUCAAUUUCUAGAAUUUUUUUAUGGCAUCGCCACAGCCACUGAAAUUGCCUAUUACUCUUAUAUCUACAGUGUGGUGGACCUGGGCAUGUACCAGAAAGUCACAAGUUACUGUCGAAGUGCCACUUUGGUGGGCUUUACAGUGGGCUCUGUCCUAGGGCAAAUCCUUGUCUCAGUGGCAGGCUGGUCGCUGUUCAGCCUGAAUGUCAUCUCUCUUACCUGUGUUUCAGUGGCUUUUGCUGUGGCCUGGUUUUUACCUAUGCCACAGAAGAGCCUCUUCUUUCACCACAUUCCUUCUACCUGCCAGAGAGUGAAUGGCAUCAAGGUACAAAAUGGUGGCAUUGUUACUGACACCCCAGCUUCUAACCACCUUCCUGGCUGGGAGGACAUUGAGUCAAAAAUCCCUCUAAAUAUGGAGGAGCCUCCCGUGGAGGAACCGGAACCCAAGCCAGACCGUCUCCUUGUAUUGAAAGUACUAUGGAAUGAUUUCCUGAUGUGCUACUCCUCUCGCCCUCUUCUCUGCUGGUCUGUGUGGUGGGCCCCUCUACCUGUGGCUAUUUUCAAGUUGUGAACUACACACAGGGCCUGUGGGAGAAAGUGAUGCCUUCUCGCUAUGCUGCUAUCUAUAAUGGUGGCGUGGAGGCCGUUUCAACCUUACUGGGUGCUGUUGCUGUGUUUGCAGUUGGUUAUAUAAAAAUAUCCUGGUCAACUUGGGGAGAAAUGACAUUAUCUCUCUUUUCUCUCCUGAUUGCUGCUGCAGUGUAUAUCAUGGACACUGUGGGUAACAUUUGGGUGUGCUAUGCAUCCUAUGUUGUCUUCAGAAUCAUCUACAUGUUACUCAUCACGAUAGCAACUUUUCAAAUUGCUGCAAACCUCAGCAUGGAACGCUAUGCCCUAGUAUUUGGUGUAAAUACCUUCAUUGCCCUGGCACUGCAGACGCUGCUCACUCUAAUUGUGGUAGAUGCCAGUGGCCUUGGAUUAGAAAUUACCACUCAGUUUUUGAUCUAUGCCAGUUAUUUUGCACUCAUCGCUGUGGUUUUCCUGGCCAGUGGUGCAGUCAGUGUUAUGAAGAAAUGUAGAAAGCUGGAAGAUCCACAAUCAAGUUCUCAAGUAACCACUUCAUAAUAUACUGCUGAAGGGCUUCUUCUUAUAGCAAGAACUCUGCACAGCAACUGCCUGGAUGUGUUUGAUUUUUUAAAGCGUAGACAUAUAUUUAUGAAUGUGCAUUUCUUGACUUCACAGCAGCCACUUGACUAAUACCUUGUGUUCCGGGAAUAACAUGAUACUAUUCAGAGGAGCCAGAAGUAAAGUUUAUUUCAUGGAUUAUUUAUGAGAGCUAAUUUAAGGAUGACUUUUUUUCUGAUUCAAAAGUGAACUUGAUUUUAAAAACCAGUCAAGAGCAAUCAAAGCAGCACAUGGUGUUGUAUACUUCAUUAGCAAGUGAGUUUGGUGUUUUAUAGGUCACAUAUGUCUGUAUCUACUUAGCCAGAUGCUUGGCCUGGUGGGACCAGGGCUCCACAGAGGCCACAAAAUGUUGCAAGUCAUGAUGGAUGGAAAUAUGUUCUAACAGCAUCUGCCUCUAUUCAAUUUAAUUCUUAUUUCUGUGUUACUCAUGUACAUUGGUCUUUCUACAUAGUUAUUCUAUCACUGGCAAUAUUUGUUCUGGUUUAGUGUUCUGUAUUUUAAGGUGUACGUAUCAUUUCUAAUUUUAAGUUAUUUUAAAAAAAUUCAUCAUAUGAAUGUUCUUGGUUCCCAUUGUGACGAUUAUUUAUUUCUGUAAAAUUUGUUUAGAAGUACGUUUUUGCAUUAUUCAUAUGCUUCCCAGAGAAGCUCAUUUAGUUAGAAAAUAAGGCAAGUUUUGAAGCCUGCUAAAUGAAGAGACUUAAGAAAGCUUAAGGUACGCUUGCUUGUCUUUAAAUCUUCAAUAUGAAGGACUAUUAAUUCCAAGAUUAAAAGUUCAUAUAUAGGCUAAAGAUGUAACUAGGCCAUUUGUAUUUGUAUUCCCUUUUAUUUCCAAAAUAAAAUGAAAAAUCUUUUUUUAAUAAUUUCAUCCCUAUUUAUAGUUUUUAUAUUAAUUUGUUUUUCUUAUCCAAGUAAAGAUGUCAAUAGGAAUUGCAUUAGUCCAAGGCCUUUUUCAUAAACUGAGCCUCUUUUCAAUUAUUUCAAUGGGACAGGAACUAGGAUAGAUGUGAUUCCUGCAUUUUUUUACCUUAAAUCUGCCUUUGUUUCUAAAGGUAGAUCAUCUUGAAUAUUUGCUUAAAAUUGCUAGUGAUUUCAUUACCAAGUUACUUGAAAAAAUGUUCUAUAUGCAUUUAAUUCUGAAAUCAGUCUACCAAGGGGCUGCUAGUAUAUGUCAGACAUGAAAACUAUUUUAAAGCUGACUUUGUUGCCUUAUCUUGAAAAGAAUCUAGAUAGGUGCUUUUAACUGGGGUAUUAACUUUUUUAGAAUGACACAGCUGAACAGUGUUAAUAAUAGUGUGUCAAGAUUGCAAAGUCGACAUACUCAUUUGGUUUAAGCAGGAAUCCUAGAAGCAAAUGGAUGGGGAUAAGAAUAGGUCAUUUUCUAUUCACCAUCCUUUACUAUUAAGGGAAAGGAAAAGAACACUAGCUAAGGAAGGGAAAGGGAAGUGAUAUCAUAAAAGUAGCAACCUUCAUUUUACAUUCUGUCUGUUUUUCUUUUUUUGCUUUGUUUUGUUUGUGCUAAUUUGGGAAUUGUGUACUCCGAAACAAGUAGAAAAGUGCUGUUUGAGGGAUUUUAUUAAAUCUUUUUUUAAUGGAAUGUGGUACAAAUUGUUCAUGUUACCAAAGCAAUAUUUCCCUGGAAUUUAAUUCAAAGUUUGUGGCAUACAACCUGAGCCUUUUCUUAUAUAAGACAAGAAUAUGUUCACAUCUUGGUAUGUGGCCAUAUUUAUAGAAUGCUGAACUCAAUGUGCAAGUUGUACUGUAUGCAGUUUUGUAAAUAAGUGAAAAUAAUUUGUUGUACUUUUUAUUCAAUUCUGUAUAGAUUAUAAAAUUAUUUUUAUUAAAUAAAUAUUUUACAGUAUAUUUUCUCUUUUUAAUCAAAA

In [34]:
mutated_post = 0

for i in range(len(mrna)):
    if mrna[i] != normal_mrna_slc19a2[i]:
        mutated_post = i
        print(f"""Mutation found at location: {mutated_post}
              Sequence for normal sequence is {normal_mrna_slc19a2[i-5:i+5]} and mutated sequence is {mrna[i-5:i+5]}
                and exact nucleotide change is {normal_mrna_slc19a2[i]} -> {mrna[i]}
              """
              )
        # Stop checking after the first mutation
        break

Mutation found at location: 1088
              Sequence for normal sequence is GGCCCUCUCU and mutated sequence is GGCCCCUCUA
                and exact nucleotide change is U -> C

In [ ]:
def print_mutated_codon(seq=mrna, start=178, end=1672, mutation_location=1088):
    """Print the mutated codon from the mRNA sequence"""
    cds = seq[start:end]
    stop_codons = ["UAA", "UGA", "UAG"]
    mutated_codons = []
    amino_acid_count = 0
    mutation_location = mutation_location
    for i in range(0, len(cds), 3):
        codon = cds[i:i+3]
        amino_acid_count += 1
        if codon in stop_codons:
            mutated_codons.append(codon)
            print(f"Stop codon found at position {i}: {codon}")
            break
        elif i >= mutation_location:
            mutated_codons.append(codon)
    return mutated_codons, amino_acid_count

mutated_codons, amino_acid_count = print_mutated_codon(mrna)
print(mutated_codons)
print(amino_acid_count)

Stop codon found at position 936: UGA
['AUU', 'UUC', 'AAG', 'UUG']
313

In [36]:
def print_mutated_codon(seq=mrna, start=178, end=1672, mutation_location=1088):
    """Print the mutated codon from the mRNA sequence"""
    cds = seq[start:end]
    stop_codons = ["UAA", "UGA", "UAG"]
    mutated_codons = []
    amino_acid_count = 0
    mutation_location = mutation_location - start 
    for i in range(0, len(cds), 3):
        codon = cds[i:i+3]
        amino_acid_count += 1
        if codon in stop_codons:
            mutated_codons.append(codon)
            print(f"Stop codon found at position {i}: {codon}")
            break
        elif i >= mutation_location:
            mutated_codons.append(codon)
    return mutated_codons, amino_acid_count

mutated_codons, amino_acid_count = print_mutated_codon(mrna)
print(mutated_codons)
print(amino_acid_count)

Stop codon found at position 936: UGA
['CUA', 'CCU', 'GUG', 'GCU', 'AUU', 'UUC', 'AAG', 'UUG', 'UGA']
313

In [156]:
mrna[1080:1120]

'GUGGGCCCCUCUACCUGUGGCUAUUUUCAAGUUGUGAACU'

In [154]:
import re
import os
import time
import pandas as pd
from Bio.Seq import Seq
from Bio import Entrez, SeqIO
from warnings import filterwarnings

from Bio.Seq import Seq

def translate_mrna(mrna_seq, start_pos=178):
    """Translate mRNA to protein sequence using BioPython"""
    
    if mrna_seq[start_pos:start_pos+3] != 'AUG':
        raise ValueError("Start codon not found at the specified position")
    else:
        print("Start codon found")
    
    # Extract the coding sequence from start position to end (or 1088)
    coding_seq = mrna_seq[start_pos:1672]
    
    # Use BioPython's translate method - it stops at the first stop codon automatically
    protein = str(Seq(coding_seq).translate(to_stop=True))
    
    return protein

# Translate the normal mRNA sequence
normal_protein = translate_mrna(normal_mrna_slc19a2)
print(f"Normal protein sequence length: {len(normal_protein)}")

# Translate the mutated mRNA sequence
mutated_protein = translate_mrna(mrna)
print(f"Mutated protein sequence length: {len(mutated_protein)}")


if normal_protein != mutated_protein:
    print("The sequences are different!")
    # Find first difference
    for i, (n, m) in enumerate(zip(normal_protein, mutated_protein)):
        if n != m:
            print(f"First difference at position {i}: {n} -> {m}")
            break
else:
    print("The sequences are identical")

Start codon found
Normal protein sequence length: 497
Start codon found
Mutated protein sequence length: 312
The sequences are different!
First difference at position 303: L -> P

In [133]:
normal_slc19a2 = 'ATTGTTGTTTTGTTTTTTGAGACGAGTACTCGCGAGTCTCGCTCTCCGCTCACTGCAACCTCCGCCTCCTGGGTTCAAGTGGCTCTCCTGCCTCTGCCTCCCAAGTAGCTGGGACTACAGGCGTGCATGCCACTATGCCCGGCTAATTTTTGCATTTTTAGTAGAGACGTGTTTTCGCCATGTTGGCCTGGCTGGTCTGAGACTCCTGACCTCAAGTGATCCGCCCGTCTCGGCCTCCCAAAGTGCTGGGATTACAGGAGTGAGCCACCGTGACCAGCCAGAAAGCTATTTTTAATAAGTAGGCTTCTCTTTCCGAGGCCTCTCTGGCTTGCTTTCTCTTTCTTTCTTCTCTTCTACTAAAGCACTGAATGTAAATACAAAGCGATTGTCAAGAAGACCACCTGTTTTCTCTCTGTAGTCCTGATAAGAAGGGTTGGAGTTTAGGGGACTAGACAATTGAATAATATCGATTAGCAGTCCTCAAACATTTTGGTCTTAGGACCCTTGTTAGAGGTGCCCCAAAAATCTGTTGGGTTTTGTGGGTTATACTTATTGAAAATTGCCATATGGTAATAAATTAAACCTGGAAAGTCTTACAAACACAAGAATATACAAGCACGTATTCTCTCATCCTATAAAGCGATGATGTCATCAGACATTATATAGCCTCTGGAGTGGAAAAGGAAATAAAGACTTAGCATGGTTATGAAAATAGATTTGAGCTCGTGGAACCTCTGAAAGGGTCCCAAGGACCCCCAGGGCTTCCTCGACCACACTTTGAGACTCATTGAGATATGTAAATACTGCCAGTTGTATTTCTTCACAGATTAATCAACTCACAGATTTGGGTGCATTCATTTGTGCAGTCTTAGAAACAAATCTTTCCCTTTACCAGTATCTTATTCCATCTGGTAGACTCATTTCTGCTGCTGATGCTTGAAAAAAGTGTCATTTGCTACCACAGGAGGAAAACGGTGCTAGATGGATCATAACATACAGAAAAGCAAGATAGTTCCAAAATGTTTCCAAGAGCTTCTGGCAGGATCTGTCATTCTACAAATACTGCACAGGAAAAATTGCTTTAAATGCTGCATCTTTGCAGTAGAAAGATTAGGATTGAGCCAGGCTGTGAGTCAGGCAGAAAAAGGCACACAGAGGGGGATGAAAGAAAGCACTGGAGAGTCTTGTCATGCTTTGCCCTTGAAAACTATGCCAAGACCTCTTTTGTGTTTTTAAATGAAGAAATCCATCATGTTTTGTGATTGCTGTAATGACTCAGGATCTTCCACCTTCCTTTTAACTATAAACCGTAGCGTAGTTAGGTGTTTGTTTTCTTTGTATCATGCTTGCAAAAAGTGACGAAATAAAGTTAAAACCCTTTAACTGGGACTCCATTACGGTTCTGCTGTTCAGTGACCAGCTTGTTCATTATTCTCACAATATTATCTACTTTCTTCATTTCAGTCTGTCTCTTAGATCCTGGGCTTCTGATGTCTTTCCATGGCGGATGAATACAATTTAAAACACGAAAGCTGCTGGAGGAAAGGTTTAACGTTCCCCCTCCCCAAGGTGAAATCTTTGCCTGGCCTCAGTCACTAAGTCTCTCAGGAGCGGAAACTGAATGGACATTCCGGAGACGGTGAATAAGAATGATAAACGGTGGTTGGGGAGAACAGCGCGTTTCTTCCAGCGGAGGACTAGGCCCACAGGACGCATTCCCAACAGATGAGCGGAGCCGACAGCAAGTGTGCCACGAACGCCAGCTGGCCGCCTCACTAGAGAGAGCTCCGCCGCAAGCCGCCGCTTTTGGAGTGGAGTTCCACATGTCCTCCGCGCTTGAGCCCTGGGACGTCAGAGGCCTGGCGTGCTGCCACCGCCCCAGTTCACGTCGTGTGACCCACGACCAATGGAAGAGCAGGCAAGTATTCCCGGCGTCCGCTGTGATTGGTTCCCGGAGTGGAGGCGGTGGCAGAGGGTGGGCCTTAGGACGGGTCTCCCTTAAACTGGGCGATCAGGCAGCGACCCTAGAGGCGTCTGTAGGGTAAAGCTGGGGGTTCTGTAGCCGGAGGCGGCGGCGAGTCCAGAACGTCCTGGCCTTACAGGGAGAAGGCGTCACTCGCGGTTACAAGTGCCTGACCCTCACTCCAGTTGGCGGAGGAGGAGAAGGAAGGGGCCGGGCCGGGTCCCCTCCCCTCGCGCCCCGGATGGATGTGCCCGGCCCGGTGTCTCGGCGGGCGGCGGCGGCGGCGGCCACTGTGCTCCTGCGGACCGCTCGGGTCCGTCGCGAATGCTGGTTCTTGCCGACCGCGCTGCTCTGCGCCTACGGCTTCTTCGCCAGCCTCAGGCCGTCCGAGCCCTTCCTGACCCCGTACCTGCTGGGGCCGGACAAGAACCTGACCGAGAGGGAGGTACGCGCGGCGGACGCGGGGCGCGGGAAGGGCGGGCGACCGGCCTGCGGGTGGGCAGCGGAGGAAGAGAGGACCGAGAAAAGCGCTCGAGCCATTCTCGGCAGAGATTTCTGATTTTGCCAGTTGGAGGTCGGCTTCGTGCTCTTCTTTGTGTTCATGATTTTCTGTTTTCTTCGGCTCTGTAGGACGAGTCTCCTGCGAAGGGCTCAGAACACGCGTCCAGAGGCCCCGTGCCTTGTGCGTCAGGCAGTATGCTGATCGTGTTGTAATGTGGCTTAGCGTGACTGCCCAGACTGGTCCAGCAGTTCCTGCTGGGGGCGAGGGGGCAATATTTTGACAAAGAAGTGAAAACAGCAAAGTGTACTTTGGACACGGCTTAGTAAATATTCATTGACTGAAAGTAGGCAACCACTGCTTTTCTGAAAGGATCTTCCCTCTACCTCCTTCACCTGCTTCCTGTCCATACCTTACTTTGTTTGCATTTGGCAGAATGGGTGGGCTTAATCAAGTAAGGACAGGACAGAAGTACAGAACATCTTAATTTGTCTTGATTTTTAATTGGGTGAGGTTGTGTCCAAGGATATCCTGCCCCTCTCTACCTTAAGACCAACCTCCAGGGATAAAGGCAGATGGTGAAACATAATTGACTTTTAATTATAGTGTTTCTTGTATTGCGAATTGTTGCTTCACAGATGTTAGTTTTGCTTCTCAGATACAAGGTGATGTCTTTGAAGGCCTTCTGTGATGTTCAGGGTAATTGAGAGCACGTAGTCCATCATCAAGAGTTTCTTGCTGATTGATTTTTTCCCTAGATGAGGGCTTACAAATAAAGTACTTCAGAAGCGCATAGTGTACTTTAGAAATGTGCTGACCTATTTAAGTGCATGGTCAAAACCAGCACTTGATTTTTGCAGAAGAAAGACAATATATAAACTGAGAAAGAAATTAAACCCAAAGTACTTCCACAAAACCGAAATAAAGCCGATTCAACACCCTCTTCCTTGAATACAACAAAGGGTGAAAGCTGAGGTCTCATGTTCTTTTTCCTACTATCAGTCAAGGGGCCACTTGAGAGCTTTTTCTTTTTTCCTACACCTGTTCCTTCCACCCTGCCTCCTTGCCCCAGGTGCTGTAAAATACTCCTCCCATTTAAACCTTACTCTTCTCTATGTGGGTAGTAGTCAGTCACTTCTTTTGAGTAGCCACTCAGTAACCCTGCATAACAGGTCAGAACAAGAGATGGCACTACCGGAATCATTTGCACACTGGCGAGATATAGTTACTCATAGTTTGTTGTTTGCAGTTTGTTTGTTGCAATGCTCCGTCATTTTCAAGGGCACTTGAGAGAGAATTAAGAATCAGTATTGACTTACGTATTGAGGGTTTCACTTGAGAGTCTGACATTTGTTCACTTCTAGCAAGTATCACTGACTTTTTGCCTGGCCTTAAATTACCCTATTGACCTGCCAGTTGTGGGATGGAGTGGCTGGGCCGTTTCTCAGTCTTGTGGATCATTACATAAGCGACCGTAACAGTTATTCATAACCTATTTGAGTTTTAATACTGATTTAAAGCAATAATGTCAAAACAGCCAAATTTCATGACAGAATGATTTTACAAGAAAATTACTGCACTGATATGAGAAAGTATGATTCTGGAGACCCAAAACAACCACTGAATCTGAGGTGTAGCCACTGAGGCAGAATTGATACTGCTGTGAACAGCTGACCATTAAAGTTTCATGTGAACTGCCATGTGATCTGCACAGTTTGTGCGCCTTTCCGGATAGTGAAACACAGGGAGAGAAACATGTTCCCAGTGTTGATATTTGAAAGCTGATCTGTTTTGTCATGTGCTCTGGGTAGAAGGTTGCTGTGTGACGTGCTACCAAGATCATGTGCTCTGTCCTATCAGAAAGCTTTTCAAGGTGAGTGAAGTGTGTTCAGGGGGCACAGAAATAAAGCAGAGTTGCCAGGCGTAGTAACTATTTGCTGATTGTGTAACAAAAAACATAAGTGTACTTCTCTTATTGCAAATTAGTTGAGGAAAAGCGTGGGATTTGAAGAGAAATCTAGTAGTCTGGGGAAGGGGTGTCTTCTCAGAGGACCACCAAATCATGGCTGATTCTCCTCTGCTTACCTTGTGGCAAACCCTACGTTTTTTTGTATAACTAATAATTGAAATAAATAGAACAACTTATTCATTACTTACTGAATGCTTGTTTTTTGCCATGGACAGTTAAATAAAAAAAATTACATGATTTTTAAGCAAAGCTAATGCTAAGTCATATTCAGCGACATTTGTATTAAAGTTTGTATTTGCTCTTAGAAGACTGCAGAAGGGCCAAGTTGGTTTGAATAGAGCTATTGTTAACTAAATCCTAAAACAAAAGGAGAGGAGAAAAAGATTTCTTCTGTCTACTCTCAAAAGTTTTTTTCTTAGATTTCAGGAAAAGCATTAATTTTAAAACAGATACCAGTGTGTAAGTTTTAAGCAGGCTAAAATTTGACTGTATGTTAATAGTTGAAGGCCAGACTTTCAGTAAAACAGATCTTTATCTCTAAAAACTTTTTTATCCTTTCATCATTGTAGCATGTGTTTTGACAGACATTTACTACCTTTCTTAGATTTTTTTAAACATTCCACCTATTTTGCCTGATATTCAGAGCCTCACGAAGTTTGGTTTTTACCTCCTTGACAGCCTTATATCCTACTACAAACCTTCTTCCCCTTACCACTTCCACATAACCAAGCTCCATTCATATTAATCTAATAGTCTTAAGTCCAGCATATCCACAGTCTCATCTGTTGACATGTACTCAAAGACTTATTCTCTTCTTGGAATAATCTTCCCATATATATCTGTTGATATCTTTGTTAGCCTTTAGGTTTCTCATCCTTCAAGGTCCATTTTGAAGAAACAACCCTGTATTTCCTATTTCCATTATAAATACTGCATATATTATATATTCCTCACTAGGTTCAATACTCCTGGAGAGCTGAGGATCTCAGTTTATTTATTTAGAGACAGTCTTGCTCTGTTGCCCAGGCTGGAGTGCAGTGGTGCGATCTCGGCTCACTGCAACGTCTACCTCCCAGGTTTAAGCGATTCTCATGCCTCAGTTTCCTGAGTAGCCAGGATTATAGGCTTGTGCCACTACTCTCAGCTAATTTTTTATATTTTTAGTAGAGTCGGGGTTTTGCCATGTTGGCCAGGCTGGTTTTGAACCCCTGGCCTCAAGTGATCTGTCCAACTTGGCCTCCCAAAGTGCTAGGATTACAGGCATGAGCTACAGTGCCTAGCCTTATTTTATTCTTTTTTTTTTAAATTTTTTAATTTTAATTTTAATTTTTATTTTTTGAGATGGAGTTTCGCTCTTGTTGCCCAGGCTGGAGTGCAATGGCGTGATCTCGGCTCACTGCAATCTCTGCCTCCCAGATTCAAGTGATTCTCCTGGCTCAGCCTCCCAAGTAGCTGGGACTACAGGCACACGCCACCATGCCCGGCTAATTTTTTTGTATTTTTAGTAGAGATGGGGTTTTGCCATGTTGGCCAGGCTGGTCTCGAACGCCTGACCTCAGGTAATCTACCCACCTCGGCTTCCCAAAGTGCTGGGATTACAGGCATGAGCCACTGCGCCTGGCCATTTTATTCTTTTTGTCACCTCCGTGCTGGTTGAAAACAATGTTGTGCAAATAACTGCCTATTAGTTGTTTAATTGAAACTTGATTCTAATTTAAAGCCTAAATCTAAATTAGAACTTAAAAATGAACATCTGTTTTCCCTTGACTTTGTAGCTCAAGAAAACACAAGCACTGATCCAAAGAGTTGTGAAAGGCACCTTGGTCATAATAAAATCAATTCCCGTTGCTCACATAGCAGATGTTACGTGAAGTGAGAAGTTGGAGTATGGACAATTAATAAGGGTCTGTAATTGGTACATTTTTGCCTGTAGGATGTTTCCCTTCAAGATTCAAAATATCAAGGAAGCATTTTTTGCTGTCATTGGAAACACTGAAAAAGAAAAGGATCTGCCTTGGAGACCCATTAGTTAAGTGCTGGAGACTGTAGTCTTTATCTCTTCATGAATGCCCTGTAAAAGCACCTCAGTGCAGATTGGAAAAGCTACTGCAAGCATTAGAATTAACCTGGAAGATAGTAGATGATTAATAGCAGTTTTCTGATTGAAGAAACCAGGCATTTTAGTGTGGCGGATTCAGAATTTATGAATTCAGATCCTTCTTCTGCCAATCCTGTGATAACTTGGGACAATTCACTTAACCTTTCTTTAAGGCCAAGTTTCCTTGTTTGTAAAATAGAGATGATAGAAGCATTTACCTTAGGTTTGTGGTTTGGATTAAATAGAGAGAATTTAGAGAAAGTGCTTAGCGTGGTGTGTAACACAGCAGTAGAGGTTTGTTATTATGATGCTGATAATAGTGTGAGTGGGGCATTCCCCCTGGGTTGATGTCTTTTAAAGGAGAAAATGCAGGTTTCTTATTTAGAATAAGTTAAAGAGAAACTATCTGGTCTTCCCCCTCTCCCCTATTTGCCTTTCTTTTTGTTTTTAGTTGTTATTGCAAGGTTGGCAGTGTTACTCTCCTCCATCTTCATTATCTAAATTGTAGTTTTGTAATAGTAGAATTAGACTCATGAGTAAAGATACGTTAAATTGATAATTTAAAGGATGAAACTTAGACAATGAAAACTTAGCAGTTAATCATTTTGGGACAACTATGGTTAAAAGTTATGTAACATGTCTAAGCACAGACAATATTATTGGAGTGAAGAGGTCATCCAAAATCCCAAAACAAAGGAAGATGAACTATTGAAGGGAGCAGTAGAGGACATTTTTAAAGGAAAGGTTTAATGGCTAGTACTTCATGGTGCTATGTTGGGGAAATTGTGAAGGTGACACTTAGTCAAACAGAGGAGGCAGTTTCAAACTTTAGAAAATGGACAGGCTGGGTGCGGTGGTTCACAGCACTTTGGGAGGCTGAGGCGGGCGGATCATGAGGTCAGGAGTTCGAGACCAGCCTGGCCAACATATTGAAACCCTGTCTCTCCCAAAAATACAAAAAATTGGCCCGGCATGGTGACAGGCACCTGTAATTCCAGCTACTCGGGAGGCTGAGGCAGGAGAATCGCTTGAACTCAGGAGGCAGAGGTTGCAGTGAGCCGAGATCACGCCATTGCACTCCAGCCTGGGTGACAAGAGTGAAACTCCGTCTCAAAAAAAAAAGAAAGCTGACAGATAGTATCTGTAAAAGTATAGGCCACAAAGGAATGACAAGTTGTTAATTAGAACACAACTGGAAATCTCAAGATTACCCTTACCTGCTTTGGTTTTCTACTTAGAGTTATTTAATGCAGCTAAGGGCACTTTTTTCCTCATTTGCTAAAATTTCCACAGTTTTGAATACGAATCATTTCTACATTTCTTGATTATTCGTTTAGGCACATAGTCAGGTGCAACAAAATTTCCTGATCAAGTGGAGCTTGCTAACTGATTTACCAACACAAATTAGACCAAAATTCATGAAGGTGAGGCCATTAAACAGATCACTTTTGTCTGGAATGTATTTCAGAAAACAGGGATTATGTTTTACTTTTATAGCTATGCTCTGCACTGGCAAGAGATTTTGCAACAATTTTTTATTGTTTGCCTAAAACCTTAGAACCTTAGCTCATATTAGACTTGAGTGAACTGAGATGTACAGGAAAGATAAAAAGAAAGTTACTATTGGTCTCAGAATGTAAAAGTCTGGGATTAGGTTGCTTCATCACAAAGTATTCAGCCTTTTACCAAAACTACCTTTCAAAAAGCACTTAAAAGTTGAGGCCACTGACAAAAGGAAGGAAAAATCTCCTACAGTGATTGTTGTTGGAAGAATGGGAATGATAGCTCAATTAATTTAGTTAATTCATACTGCCCCAGATGTCCTTGTCAGCTTGTCCTCTAGTCTTCAGACTTTGTGAATAAATCAGGTGGAGTAAGTAATTTACATGTTGTGTCTCATTTACTTTTTGCAACAAACAACCGCCCTTTACTGATAATGGAGATTAAGGCTAAGGGGAACTAAAAGAATGTTGTCTACAATCACACAGCAAGTGATGGAACTGAAATTCCTGTTGGGGTCTTTCTGGTTTAAAGTTTATTTTAAAGATCATTTCTACTATATCCCAATTTTAAAATATGCATTAGAAAGAAAACAGCAAAAACTTCTTTTTTCTATTTAAAAACAAGCAAAAAGAAGGACATAAAAGTTGCCTATATTCCTGCCATCTAGAGAGACTTAATTCTGTCAAGACTGTAGGACACATTGACCATCTTTATTTGTTCCTCTGCCCCAAAAGAAACAAAACTTAAAGTCAGAGAAGCTTAATGAAACAGTAGGATAAAGGCTCCCTATCTTGTGTCTAGAAGTAAGAATTGACAGTGATTCCGTTTTCAAAGCATTTATTGAATAGTATCTTCCAAACAGTATGCTGGCTTTTAGACAGGTTATACAGGTGAATGTAGGGGTCTATCCTTAAAAAGCCTATAAGGCAGTTGTTCTCAACTCTGGCTCATTTAAAACTCTATTGGGAAGTTTTTAGAAAATATCTGTGGCTGGGCATTTTTTTTTTTTAAAGAGACAGAGTCTTGCTCTGTCATACAGACTGGAGTGTAGTGGTGTGATCATAAGTCACTGCAGCCCCAAACTCCTGGGCTCAAGCAATTCTCCCACCTCAGCCTCCTGAGTAGCAGCCATAGGCATGTGCCACAACGCTTGGCTAACACATTTTTTTAAAGCTTCTTAGGAGATGCAGCCATGGTGAAGAGCCAGTATTATGAATTAATTGGGGAAACTGATGCATATAGATCAGTATTAGGAGAGTTTGAGGCTAGGCCAGATGGCTCACATGTCTGTAATCCCAGCAGTTTGGGAGGCTGAGGCTGGTGGATTGCTTTGAGCCCAGGAGTTTGAGACCAGCCTGGGTAACGTGGTGAAACCCTATCTCTACCAAAAAAAAAAAAAAAAAAAAAAAAAAAAATTAGCTGGTTGTGGTAGTACAGGCCTGTAGTCCCAGCTACTGGGGAGGCTGAGGTGGAAGGATCACCTGAGCCTCACCTGAGGCGGAGGTTGCAGTGAACCATGATTCTGCCACTGCATTCCAGCCTAGGTGACAGAGGGAGACCCTGTCTCAAAAAAACAAAAAACAAAACCAAAAAAAAAAAAAGGGTTTGAATGTTGTAATACAAGTACTTTTGGCTTCCGCAAAGTCTTTCTGAATAAGGAAGTCTTTGAACTAGGCCTTGATTAATGGGAAGAATTTATTAGGAAAAAGATGATGGTATTGGGGATAGGAAAGGATATTTCAGGCTGGGCGAGGTGGCTCACCCTTGTAATCCTAGCGCTTTGGGAGGCTCCTCATTTGAGGTCAGGAGTTTGAGACCAGCCTGGCCAACATGGTGAAACCCCACCTCTACTAAAAATACAAAAATTAGCCAGGCGTGATGGTGGGTCCCTGTAATCTCAGCTATTCGGGAGGCTGAGGCAGGAGAATCACTTGAACCTGGGAGGCAGAGGTTGCAGTGAGCCAAGATCGTACCACTGCACTCCAGCCTGGGCGCAGAACAAGACTCCATCTCAAACAAAAAAGAGAGAAAAGACATTTTCAAAGTTATCTGAACTGCTGTTGTCAAGGTTGAGATCTTTGAGGTATTTGTAGGTTGTTTTTTATGAATAAATTCTTTATGAGTATTCCAGGTCCTTTCATCACTAATGTTTTTTGTTTTTTTTTTTTCTCTTTCTACCAGGTCTTCAATGAAATTTATCCAGTATGGACTTACTCTTACCTGGTGCTACTGTTTCCTGTGTTCCTTGCCACAGACTACCTCCGTTATAAACCTGTTGTTCTACTGCAGGGGCTCAGCCTTATTGTTACATGGTTTATGCTGCTCTATGCCCAGGGACTGCTGGCCATTCAATTTCTAGAATTTTTTTATGGCATCGCCACAGCCACTGAAATTGCCTATTACTCTTATATCTACAGTGTGGTGGACCTGGGCATGTACCAGAAAGTCACAAGTTACTGTCGAAGTGCCACTTTGGTGGGCTTTACAGTGGGCTCTGTCCTAGGGCAAATCCTTGTCTCAGTGGCAGGCTGGTCGCTGTTCAGCCTGAATGTCATCTCTCTTACCTGTGTTTCAGTGGCTTTTGCTGTGGCCTGGTTTTTACCTATGCCACAGAAGAGCCTCTTCTTTCACCACATTCCTTCTACCTGCCAGAGAGTGAATGGCATCAAGGTACAAAATGGTGGCATTGTTACTGACACCCCAGCTTCTAACCACCTTCCTGGCTGGGAGGACATTGAGTCAAAAATCCCTCTAAATATGGAGGAGCCTCCCGTGGAGGAACCGGTAAGCTCAGCCTTAAATATCTTGTAATTGCTACTATGGGGGCTGGACCCGTGGTGAAAAAAACAGCAAACTCCCTCTTGGTAGATCTTGTATTTATTTGGATTCATGTTTTATCCTGAGTTGGTTTATTGCTTTATTCATTCATTCATTCATTCATTCAAGCTATGGTTTATTTATATTAGGGATGACACATTTATTTTTTCCTGGAGTGCGTGACCTCCAAAGTCAGACTGATACAGCATTATATTGTTCATGTCAGAGATGCCTTGGATTGCAAGGGCTGTGTCTTCATCTTTTGAGTGTTTGGCATATAAATAAAGCACTCAGAAAATTGTTGCTAAATGAGTAGATGAAATGATTCTAATAAATGATTAAGTATCTACTTCTAGTTTCTGAATTGAAGCCCAAATTATTATTATTATTATTATTATTTTTGAGACAGAGTCTTGCTCTATTGCTGAGGCTGGAGAACAGTGGTGCGATCTCGATTCACTGCAACCTCCGCCTCCAGAGTTCAAGCAGTTCTCCTGCCCCAGCCTCTCCCTAGTAGCTGGGATTATGGGCGCTCGCCACCACGCCCAGCTAATTTTTGTATTTTAGTAGAGACGGGGTTTCATCATGTGGGCCAGGCTGGTCTCGAACTCCTGACCTCAAGCAGTCCACCAGCCTCAGCCTCCCAAAGTGCTGGGATTACAGGCGTGAGCCACCGCACCCAGTCATGAAGCCCACAGTATTTAAGGGTAAGAAGTTAATTTCCTCTTCTGTGCTAGAAGGGATATCTGTTATTTATTTTTCAAATGACAATTTGCTGAAGTGAAGTAGTAATGAATAATACAGACGAAGAGATCACAAGAGGACAGTTTGAGGTGGTGATGGAATAAATAGTAAAAGTGTGTTATGAAGCTGTCTCTTGGAAGAGAGAGGTATGGCATTAAAATAATTTATCCATCTGTTCTGTCTAGCCAGGAAGATGAATTCCTTTCCCTAGACACCCACCCTTTTTTTTTTTTAAATATTCAAGTGTTTTTTTTGTTTCTATTAGGTTATAAGCTGTGAGGAACAAAGTTAATTCCAGCCACACTGTAGTCTTAGTTTTCCTGGGACATGTTTGGAAATAAGCCTATTAACATTCCAGCTTTGTAGGTGGCCTCAGTCGGACTGAGCTCCATAAGCTTTGTAGGCTGGCTGATAATAAAGAACCATTATGAGTAAAGTCTTTCATTCTCTACTGAGAGTTAACTGAATTGTTTAAATGTGGCATCTAATGTCCTCATTGAAAATTACTCTCTTTTCTCTATCCCCGTTCTTCAGCTCTCAAATTACTACTTGAAATTTAGGTTATCATCCCAGAGAGCCTGGGTAGACTTGTAGAGCCTGGGCAACCCTCATCATGAAACTCACCTTGATTACCAGGGCACCTGTGAGCACTTTTTGTCAGAATGACCAAGGATTAAGTGGCAATGAAATGCTGATTTTTTTCATAGTTTGTTAGGTGATATTAGAGAGTCAACAGAGGGTTGATGGGGGAGGGAAGGAGGTGTGTAATCATTTCATAGATTTTATGAAGTGGAAAAAAAATAAAGACACTTCTTTATCTGTTTTGAATGTGTTACAGTGGCTTTAGCTAAAATTAACGTATATACAGATAATATGTGTATAAATATATATTTTAGATATTAACATATTGACCATAGTTCTAAAGATTTTTATAGACAGTTTCAAACTTTTTTGAATATAAGTAAGAAACATAGAAAACATTTTACATAGAAAACCTGTACATACATAGGTATGTATATATTTTATATATAACAGAAACAAGTTTTACAACAGTGTTTTATTCTGATACATTCTTTTATTTTTTTTAAATTCAGTTCACTGTCCTCTAAATCAATTTTATTGCCAACTTATGGGTGATGACCTATAGTTTTAAAAACTGTTCTAGATCAACTTGAAATACTTGTTTATAGATACACAGTGTGTCAGTATTTTATATACTGAAGAATTGTAGAATTTTAGAGTTAGAAATGACTCTAATCACAAGTCATAGAAAAAGCAGAGCATTTTAAAAAGAGATTAGATTTCATCAAGACTGTCCTTTTAGAGATAAGGATTAGGATCAGAGATTAGCAACTTATGCAGAATTGTACAAATATACTCTTGAACATAATTTAAAAGTGTGTATGAGATCCAGTTCTTTCTAAACCTTTCTCGGTGAAGTCTTTTAACTGGGGTAACAATGTCAGAACCATCATGTCAGTTACACTGTTTTCAGAATTAGGATTCAAGTCAGTTCCCTGATATCCTAGGCTCTGCTACTGATACCATAGCAGATGGGCAGTGCTGCTTGGTATTGGCACTGACTGGCCCTAAAATGCTGCTGTTTTTCTTTGGCAAGCATGAAGAAAATTCAGAATATGGATATTAGGGATCACAGAGCTATTTTAAGTTGACAAGACCTATAATTAAACCATAAATTATAATTGTGGTAATTATTGAAGAGTAGGTAGGTAGGTGGTTTTATCTTGATTTTTATAGAAAGAGAAAATGAAGTAAGAGGAGTCTAAGTGATAGCTCATTCTACAAGTTACCTTAGAGTATTTGTGAGTTATTTTTAAAGAGAGTCTATTGCATTGGGGCAAAGGGTGCTGATCTTGCAGAAAGAAGAACCAAAGCTGGTGACTTTCTTTTACAAGCAGAGCTGGATTCATTATGTAGTTGGCTGATTGGTGAAACTGATTTATTTTGAGTTCTTCATCTATTAGAAATGACATAAATTAAACCACTTCTTTAGCACAGGTTCTGACATGTAATTAATACCTAGTAAATGATTCTCTTAATATAGCCATGCTTTTATTTGTAGTTTGATATCTTTTACTACTAGTAAGTGTTCTTTCTGTGTCTGCATGTCTAAGGTCTCTAAACAATGACAACAGTGAAATTAATGCTTCCACTTTGGTATTAAATAATGTCATTTCTAGCAGCAGGGTGTAGTGAGTTACCACCTACCTCCCTCACCAAAACCCATAAAAATAAAAAACTACAATAAACCCTGAGAACCAAAATGAACGAAAATCTATTCGCTTCATTCATTGTGAGTTTTTAAGAAAGTGAAGTCCAAACCCTAGTTCTAATACTTGGGCAAGTTACTTAATTCTGTGAGATTTAGTTTCCTTATGTACATATCTACCTTATACAGTTATTTTGAGTATTTAAAGCTTTCAAATGAGTTTACATAGTAGGTTTCCAATAAATGGTAATTGCTATTATTACTATTATCATTATCATTACACGTGAATAATCCGGAACAGCTCTGTACTTTTATGGTAGATAGTCATGTATTTGTGAGGTTGTAAATAGAGCAATCTTTCCTTTTCTCTTTGAATTAATCACCCCTGGTCATCTTCATCATCATCATCATCACACCTCCTGTTTATTTTGACCTGGGTATCAGATACTGTGCTAAGAACTTTAGAGTCAGTATGTTATTTGATTCTTATTAAAACTCAATAATGTAGATATTTGCTCATTTTACAGAAGAGGAAACTAAATTTAGTTAACTGACTTGCGCAAAGGCACATAGGAAGTGGCACTTTAAAACTTTCCAACTCAGGCTGGGCATGGTGACTCACACCTGTAATCCCAGCACTTTGGGTGGGCAAGGCAGGCAGATCACTTGAGGTCAGGAGTTCGAGACGAGCCTTGCCAACATAGTGAAACACGATGTCTGCTAAAAAAAAAAAAAAAATACAAAAACTAGCTGGGCGTGGTGGTGCATGCCTGTAATCCCAGCTACTTGGGAGGCTGAGGCAGGAGAGTTGCTTTAACCCGGGAGGCAGAGGTTGCAGTGGGCTGAGATAGTGCCACTGTACTCTAGCCTGGGCAACAGAGACTCTGTCTCAAAAAAATAAATAAATAAATAAAATTTCCACCCATATCTAGTTGACTCAAAAACCACCACTACAGTAGAAACTTCCATTCCCTGATAGAGGGAAGTAATTGTTAAAGATTTTTAAATTTATAAAACAGCGTCAAAATCTTATGTTCAAATGAAATCTGAAACTAGATGCCCGTTATGATAAGTAAATAAAAATTGAGCCTTTCTGATTGAAACAGGAATGCAGGTCTGATAATTTTACATACTTGAGCCTGTTATTCATCCCACATGAAACTCTTAAAGCTCCATGGAACACAGTGAAGGCCACTTATTAAATTAGAGCATGCATGATTAACTATGAGCAGCTCAGAGTTTTGATGTAATAGAAATAAACCTTTGTTTGTAGATGTAATTTAACAAGAAACATAAAAGGTAATATGTCAAATGCTACTTTATAAAGTGTGATTCATATAAGCTTAACATTTGAAGCCTAGAAAACAGCATAGAAGGAAGCCTGCAGATTATAGCACGAGGTGCTGATTTTATAAACAGGACCTGCCATCTTTTCTTTTTGGCATGGCCAGATAATAGATTGAGTAGTTATTAACCTCTGTGTGTGGAATTCATTATTATGTAATAGATCTAAAGTTCTCAAATGCATTATACTGGGCATTATTTTATGTATGCCATGACTTTTTAAGCTATGCAATAAAAATAACACTAATTGAGCCCCTCTATAATAAATATATACATTATCTAGTGTAACTCTGTATAATCTTTTGTGGATAGGTTTTATTGTTATCATTTTCATTTTCTAGATGAGAAAAGTAAGGCTTTCTTATCAGTTTATGGTAGGATTTCTAATAGAAACTTGTGAATCCTTTTAATAGTTCCATTCTTCCAGGAATATACTTTCTTTTCTTATAATCCTTCCAGCATCCTTGAAAGTTTTAGATATCCCAGTTGTTTTCCAAGTTATATTGGTTAAGCAACTGAAGCTAAATAGTAAAATTCTGATGTAGTTCAATAAAACTGGTGGACCTTGAATAAAGACTTATGAAAATGTGCTTGGTACCATTCACTCACTCTTAGCAAATTCACATTATATATGATTAACAATTGTCTTGTGATTTGTTTAAATTCACAAGGTTTGCTCTCATACACAGTGCCAAGAAATCAATCTTGTAACAGCAGTATGTTGTACTTCTAGGTGGTTATCTTATGCAAATTCATCAAGTAGAATTTTCAAGTGTCGGTACTTCTTTCTCTGAGTTATTTTGATTAACCTCAGTACTCCTCCCTGAATTTTGGAAAGGGGCTGTAGTAATGGTACTTGAAGGATATCCCCCTCTGGGCTAAACAGCACAAAGAAGGAAGCACCACACTGGGGTTGCTTTGGGATGGTATGAGAAGGTAAAACAACGATGAAACTCGGATTCTCAGTCCAGTGAGGTTTTCTAGCCTCTGAGGGAGAAAATGGCCTTTATTTAACTAATGTTGATGGTCACTGTTACTGTATATAAGAGGAGAAAATATCTATTAATTTTATAAAAATGATATATATGGTGTGTGTGTATATATACACACACACACACACACACACACGTTTGTTTTTTGAGACAGAGTCTGTCTCTGTCGCCCAGGCTGGAGTGCAGTGGCGTGATCACGGATCACTGCAGCCTTGATCTTCTAGGTTCAAGTGATCCTCCCACCTCAGTCTCCTGAGTAGCAGGGACTACATGTGTACACCACCACACCCAGCTAATTAAATTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGGAGACGGGATCTTACTATGTTGCCCAGCTTGATCTTGAACTTCTGGGTTCAAGCATTTCTCCTGCCACGGCCTCCTGAAGTGTGATGATTCCAGGTGTGAGCCACTGTGCCTGGCATCTACTTATTTTTTTAAATTAAATGTTACAGAAAGCTATATAAAAAATAAAAAATCACCTGAACTACTACCACCCAAAGATTAGTGAACTTCTTTTCAAACATCTCTTTTCCTATATACATATGTACGTATACATTTTATAGTAAATGAAATTGTGATCTACATGTAGTCTTGTAACTTGCTGTTATTTTACTCAGTGGTATATTGTACTCATCTTTCCATGGCTCTCATTTTGCCTTTCCATGTTAGCCACAAAAGTAAAATTTTCTGTGGGTTTTTTTTTTTTTTGGTAGAGATAGGATCTCACTTTCTTGCCCAGGCTGGTCTTGAACTCCTGGGCTCAAGCAATCCTTCTGTCTTGGCCTCCCAAAGTGCTGAGATTATAGACATGAGTCACTACACCCGGCCTTCCCATGTTCTGAGCAAGGCCCAGGGATTACAGTAACCTTTGGTAGATTAGTCCTTTCATACAGTTGAAATCAGAGATATCTCACAGAGTGTCTGACATCTCATATTGACTTCTTGGGATAGTGCGTAGCTCAGTAATGTCTTGCTTCACTCAATTATAAGCCCAGTAGCTTTATTTATTACTTTATTATAATACTATTTCTCATTGTTTAAATATTAAGTAATATAAAAAGTTTAAGGAAGAAAATTTAAATCACTAAGAACCCACCACCTAGAGAGAACTGCTAATATTTTGGTCTACTTCTTTCCAATATTTCTATCTTAACTGTTGGATCAGTCTGTCAATTATAACGATAGGAGGCCTTAACTGAATAGTGATTTATTAGGGTTGCTAGTCTGTTGCTTATTATTATTCTTGTTATGTTGTTTGCCAGTTTATGGGAGATGTAGATTACAGACTCCCATTGGCTGAAGCCTGCGGTCTCTTTTCATCATCTTCATTTTGTAAACAGTACATCTTTTGCTGGGTTGATTACATACAGCTGTGTTAATGCTATAGTGCATTTAAAGCAAAAATCCTATGAGAACATATTTTTCGCCAGAGGGGATAAATGTATTTGTTAATAAGTTTATGAAGTAAGCAGTTAGTTTTCACAAGGAAAAAAGTCTGTTAGGTAAGTAATTGGGCCTGTAAATTGCTTTCTATATAATTGCCTTCATCAGAGTTTGAGCATTGTTCCCTTTTGCTATGTAGGAACCCAAGCCAGACCGTCTCCTTGTATTGAAAGTACTATGGAATGATTTCCTGATGTGCTACTCCTCTCGCCCTCTTCTCTGCTGGTCTGTGTGGTGGGCCCTCTCTACCTGTGGCTATTTTCAAGTTGTGAACTACACACAGGGCCTGTGGGAGAAAGTGATGCCTTCTCGCTATGCTGCTATCTATAATGGTGGCGTGGAGGCCGTTTCAACCTTACTGGGTAAGCAATGCAGGATAATAGAGGGTCGTGGTGGGGGAGGGATTCCTCTGGTAGTTAAGCCAGCCATAATCAGATTTATTCACCCCTCCCAAATTTGAAATAGCCTCAAAAAATGATTATTTTGAGCTAGATTTTACAATTTAGGAGGACAACTTAGAAGTACTCAAGTGGAGCAGGACTATGACTAACAAACTGGAATTTTTTTATAAGCTTTGAGTAAACCTAATATAATAATTTTCAAGATTGTTTATCCAAGTTTCCATTATCTCTGTATTTACTGGGTAGTTTTGTCACTTGATGTGAAATTTTGAATGGCAATATATAATAGTTTATAACAATAGTATCTAATATTTGTTGAATGTTAATATGTGCTAGGTACTGTTCTATGGACATTATATACATTAACTCAATCCTCACAAAATTCCTGAGATAGGTAGAATTTATCCCCATTTTGCAATGGAAACTTGGGACTGGTAGGTTAATAACTTGCTCAAGGTCATATGGATGGTAAGTAGTAAAGTCAAGACTTGAACTCAGGCAGGATGGCTTCAGAGCCTGTGTATTTGACCATCTTACTCTATTGTTCATTTCTAATTTGTTGACCTACCTCCTGAGGTTGTTGGATGGTGTTATATGATTTCTGTAAACACTTATTATCTGTCTTGGCCCTCAGAAAACACTTCATAGATTTTAGCTATCCTTATCATCATCACTGTTTTACCAAAAGGCAGAGAAGCCCTTTTGCCATGTTCTAGACTGCTCCTTGGTTTGAAGGAGAGATGACTCATCCTGCCATGATGCCAAATTAGAAGCTATGGTTCTTTTTGACTCTTGCCTCTGCTTCAGCTGCAGCATTTTTTTTCCTTAGCAATGTCCCTGTGTCTTTGTCCTGCATTTTCATCTCATTGCCACCTCTCCTAATTCAGTCTGTCATCTCAGTGGCTCCATTTTATTGATTCCATCAAGTTCAGAAATTTCTGTGTGAGTTTCAAGGCCCTCCATAATCTTGAGCTATTCTGTTTATAAGTTTGCAGATTTTAAAATTTAATAATCTAAGCTGAGTTTTTAATTTATTGCAACAGCATTTGTGTAGCAAAATAATTGGATTTTTTTTGTTTGTTCTGTAGGTGCTGTTGCTGTGTTTGCAGTTGGTTATATAAAAATATCCTGGTCAACTTGGGGAGAAATGACATTATCTCTCTTTTCTCTCCTGATTGCTGCTGCAGTGTATATCATGGACACTGTGGGTAACATTTGGGTGTGCTATGCATCCTATGTTGTCTTCAGAATCATCTACATGTTACTCATCACGATAGCAACGTATGTATTTTGGCTCATAGAAGCCTTAGGAAAAATTGTAACAGGATAAATTTTTTGGTTTCTTTACAAACCAAAATATTCAAGTTTCTAGTTAAATGAGGCAAATGGGAGGAAGCATTGTATTATATGTGCATTATCAGTTTTTCTCCTGAGGAAGCATTTAGGCAAGTTTTGTTTATTCCCATGTTTGTATGTTCCTACTGTTTTCAGATGTTTGCATGAGATTTATATCATTTAGTTGCAGAATGTTTTCATTTGGTTGGAAAGGCAATTGACAGTAGAAAGAAGGACTCTTCATGTTTAAAGATAAATGTTTACTTTTATTTAGAATAAATATTATAAGTACTCCAGAAGTAATTCTTATTTATTCACTCTTTTATTTTTTTTTAAGTTTTCAAATTGCTGCAAACCTCAGCATGGAACGCTATGCCCTAGTATTTGGTGTAAATACCTTCATTGCCCTGGCACTGCAGACGCTGCTCACTCTAATTGTGGTAGATGCCAGTGGCCTTGGATTAGAAATTACCACTCAGGTAAGATCTCTCCTTTGGCATCGAAGGTAGTATGTGTGACTTGATCAGGGTGACAGAAGTATATGTATGCTTAATGAAAACAAATCCAAACAATAGGGAACAGATGTAAAGTAAAAGCATACCCTCCTTCCTTCATTCAACATCTTCTCCCCTATCCTTAGTTCTTTTCTCCTGGGAGGGTGTTGGGATTGTCAGGTCTTAGAACATTCCCGAGTGTAACTCATCAGCCCAATGGGGCTGTTTCAGCTGAGAGGTAATATTGATTCCTTACAGACCAAGACCTTCTGCTTCCTCATCCATTATTTCCCTCTATACTTAAATCTATGCTTGGAATACTGTATCCCATGTTTGAGATTCCCTGCTTCATCTCACAACTCTTTAAGTCTCCTCCCTTCTTTATTTAAAACACCCCTCACCCAAATACCACGGTAATGCCTTGCTGCTGATGAACAACATTATGATTTGTAACTTATGACTATTGAGAAACTTGCACCAACACCCAACAACAATGTGAATACTTTTTACGTTCAGGAATTGTATAGTTGTATATGCCTTCATGCATTGTGAGTTTTAAGTATATCTTGTTTTGTACTTTGGTAAAATGGGCAACTGAATGAATCAAGAAGTATTTACTCCCACCCCCATCCCAACCCAAATGATTTCTTCCCAACATATTAGCCGTAATTAACTTTGTTTTTACTGAAGCGATCTAAGAGAGAAATAGTAATAATAGACAATGTGCATTGAGTGCCTCTACGTGTCAAGTGCTTTATATAGGATTTGTAGGGTTGCTGTATTAGACATGAAGAAGATGAGTCTGAGAGATGTTAAGTGACTTGTCCATACCATCACTAGTAGTGTTCCAGAGCTTAGAGTTAAACCAACATCTAACCCCAAAACTTATTTCAGGATGGAAAGTAGGAGAGAAACTTAAGTGCTTGCCATCCTCCCTGTATAAGGGAGAGTTCCCAGGACTATTACAGTTGAGGGAAACATGGCTGTCATTGGAAGTGGAAATTTGTCAGCAGATTCTTATAGAAATGGTGGATTTAAACACGTGGAATAATAGGATTTTATGGGTGGTGCTGAAACCCTAACTGCCATGATTGATTAATGGCTTCCTGCAGAAGTGTAGCCAACATTGAAAGAAACTGGCTCAGTGATTTAAGGCCATACTCTCATTGTACTTTTGAACCAGTTTGTAAGTATTTAGTATGTTATTTTAAGAAGATGATGATGATGATGATGTTAATAAACCATATAGTCACATTAAAATTTCGCTTAGGGCATCATCCGCCGCAAACTAACACAGGAACAGAAAACCAAACACTGCATGTTCTCACTCATAAGTCGGTGTTGGACAATGAGAACACATGGACACAGGGAGGGGAACAACACACATTGGGGCCTGTTGGGGGGTGGGAGGCAAGGGAAGGGAGAGCATTAGGACAAATACCTAATGTATGCAGGGCTTAAAACCTAGATGATGGGTTGATAGGTGCAGCAAACCACCATGGCACACGTATACCTATATAACAAATCTGCACATTCTGCACATGTACCCCAGAACTTAAAAAAAAAAAATTGTCTTAGGGAAGAATTCTTACATTAAGTAATCCTGTAATGGAATATAGTTGACCTGCCGCTGCCCTCTTCTGGGGAAAAATAGAGAAGTTCTTGATCTTCAGAATTTGGCCTATTTGTACCCACCTATCAGCTTGAAGGCAGAGACCAGGACTGAATTATAACAATAACAGCAACAACAATAAAAGTAATACTAACAGCATTAGCATTGTGCTAATAAGCATTTATGATCTCACTGATGGGTACCAACATCGCTGTAAAGTGAGAACTACTATGAATTCCATTTTGTAAGTGAAGAAGGGCTCAGAGATGAAGTATCTCAATCAAGTTCACGCAGCTTGTAAGGGATGAAGTCAGGATTCACACTCAGGCAGTCAGGCTTTATTTAGTACCACCGTGCTGTGATGCTGCTTTGTGTCTTCAGGGTCTGGCACGTGGTGTAAGTATGCAATATTTTTTGAGGCTTTATGGACAAATTCTGAATATACTTTATTATAGAGTAATCCTCTTGTCATTGATAATTCAATAAACTGCTTTTCCCCCTTCTAGTTTTTGATCTATGCCAGTTATTTTGCACTCATCGCTGTGGTTTTCCTGGCCAGTGGTGCAGTCAGTGTTATGAAGAAATGTAGAAAGCTGGAAGATCCACAATCAAGTTCTCAAGTAACCACTTCATAATATACTGCTGAAGGGCTTCTTCTTATAGCAAGAACTCTGCACAGCAACTGCCTGGATGTGTTTGATTTTTTAAAGCGTAGACATATATTTATGAATGTGCATTTCTTGACTTCACAGCAGCCACTTGACTAATACCTTGTGTTCCGGGAATAACATGATACTATTCAGAGGAGCCAGAAGTAAAGTTTATTTCATGGATTATTTATGAGAGCTAATTTAAGGATGACTTTTTTTCTGATTCAAAAGTGAACTTGATTTTAAAAACCAGTCAAGAGCAATCAAAGCAGCACATGGTGTTGTATACTTCATTAGCAAGTGAGTTTGGTGTTTTATAGGTCACATATGTCTGTATCTACTTAGCCAGATGCTTGGCCTGGTGGGACCAGGGCTCCACAGAGGCCACAAAATGTTGCAAGTCATGATGGATGGAAATATGTTCTAACAGCATCTGCCTCTATTCAATTTAATTCTTATTTCTGTGTTACTCATGTACATTGGTCTTTCTACATAGTTATTCTATCACTGGCAATATTTGTTCTGGTTTAGTGTTCTGTATTTTAAGGTGTACGTATCATTTCTAATTTTAAGTTATTTTAAAAAAATTCATCATATGAATGTTCTTGGTTCCCATTGTGACGATTATTTATTTCTGTAAAATTTGTTTAGAAGTACGTTTTTGCATTATTCATATGCTTCCCAGAGAAGCTCATTTAGTTAGAAAATAAGGCAAGTTTTGAAGCCTGCTAAATGAAGAGACTTAAGAAAGCTTAAGGTACGCTTGCTTGTCTTTAAATCTTCAATATGAAGGACTATTAATTCCAAGATTAAAAGTTCATATATAGGCTAAAGATGTAACTAGGCCATTTGTATTTGTATTCCCTTTTATTTCCAAAATAAAATGAAAAATCTTTTTTTAATAATTTCATCCCTATTTATAGTTTTTATATTAATTTGTTTTTCTTATCCAAGTAAAGATGTCAATAGGAATTGCATTAGTCCAAGGCCTTTTTCATAAACTGAGCCTCTTTTCAATTATTTCAATGGGACAGGAACTAGGATAGATGTGATTCCTGCATTTTTTTACCTTAAATCTGCCTTTGTTTCTAAAGGTAGATCATCTTGAATATTTGCTTAAAATTGCTAGTGATTTCATTACCAAGTTACTTGAAAAAATGTTCTATATGCATTTAATTCTGAAATCAGTCTACCAAGGGGCTGCTAGTATATGTCAGACATGAAAACTATTTTAAAGCTGACTTTGTTGCCTTATCTTGAAAAGAATCTAGATAGGTGCTTTTAACTGGGGTATTAACTTTTTTAGAATGACACAGCTGAACAGTGTTAATAATAGTGTGTCAAGATTGCAAAGTCGACATACTCATTTGGTTTAAGCAGGAATCCTAGAAGCAAATGGATGGGGATAAGAATAGGTCATTTTCTATTCACCATCCTTTACTATTAAGGGAAAGGAAAAGAACACTAGCTAAGGAAGGGAAAGGGAAGTGATATCATAAAAGTAGCAACCTTCATTTTACATTCTGTCTGTTTTTCTTTTTTTGCTTTGTTTTGTTTGTGCTAATTTGGGAATTGTGTACTCCGAAACAAGTAGAAAAGTGCTGTTTGAGGGATTTTATTAAATCTTTTTTTAATGGAATGTGGTACAAATTGTTCATGTTACCAAAGCAATATTTCCCTGGAATTTAATTCAAAGTTTGTGGCATACAACCTGAGCCTTTTCTTATATAAGACAAGAATATGTTCACATCTTGGTATGTGGCCATATTTATAGAATGCTGAACTCAATGTGCAAGTTGTACTGTATGCAGTTTTGTAAATAAGTGAAAATAATTTGTTGTACTTTTTATTCAATTCTGTATAGATTATAAAATTATTTTTATTAAATAAATATTTTACAGTATATTTTCTCTTTTTAATCAAAATTGTTTTAAATTTATCTTCTATTTCAGTAGGAGCTTTAGATTATATCTTTAAATATTTTAATAATTTATCCTAGGACAAATTTCATATTAAGTCTTCCCCTGGTCTAACTTGCCTAGTTAACCTTTTGTTATCTTTTTAATTATTCCATTGCTTTGTGATTTTTACCTTTGACTCTTCCCCCTTATTTCAGATGTTTTCCCCCTTTTTTTTGGCACCCCGTTGCACTGTTTTTTTTTTTTTTTTTGGTTTTCATGTTGGCACTGCTCTTATCTCTTTTTAAAGCATTCTTCCTTAAAAAAAAAAAAAGACACTCTCTTTGATGTTAACTGAATTTTTACAATAAAGGAAATTAAAGCAAGAGCAGAAAATACCACCTTGTTCTGAAACTTCATAGCCTCTTTGTTCCACCTCAAATTATTCTGATACCCAGGGAGGAATCTTCTTGCCATGAGTTGAGAATCATTTGTCCATTATATCCCAGAAACCTAATCAGTATTTTCTTACAGTATCCAAATGAGTACCATTTTTTAATATACCATTTCAAAATCTACTTAAGGCATTGATTTCGCTGCTTATCACCAAAGTCCTGGAAATTTTTCATGCAAAAATAAATTTTTTTTTTTTGAGACAGTCTTGCACTGTTGCCCAGGCTGCAGTGCAGTGGCAATCTCGGCTCACTGCAAACTCTGCCTCCTGGGTTCACGCCATTCTCCTGCCTCAGCTTCCCGAGTAGCTGGGACTACAGGCACCTGCCACCACGCCCGGCTAATGTTTTGTATTTTTAGTAGAGATGGGGTTTCACGGTGTTAGCCAGGATGGTCTCGATCTCCTGACCTCGTGATCCGCCCGCCTCGGCCTCCCAAAGTGCTGGGATTACAGGCATGAGCCACTGCGCCCGGCCAAAAATTTTTTTAAATATAGTTTTATAGCCCTATAGTTTCATTGCCTGTGTCTTATTACCTTTCAGATTGGAAGCCTTCAGACCAGGGACCATGTCTTATTTTTGTTTTTTGTTGCAAAACAGATTCTGGTGTCATGTGAACATTTAATTATATAAATGGTATGTGATGGACTCAGCCACCTGCCAATACAATAGTTAAATGCTCATCTTTTTAAATTTTTATTTTAAAGAGTCAGTGTTCCTAGGCTGGAGTACAGTGGCACAACCACAGCTCACTGCAGCCTTGAACTCCTGGGCTCAAGCAGTCTTCCTGCCTCAGCCTCCTAAGTAGCTGGAAATCACAGGCGGGTACCAACACACCCAGTGAATTGTTATTTTGTAGAGATGGGGTCTCACTATGTTGTCCAGGCTGGTCTTGAACTCCTGACCTCAAGCGATCCTCCTACCTTTGTCTCCCAAATTATTGGGATTACAGGCATGAGCCACCTTGCCCAGCCTTATTCTTACTGTATTTTTAAATGCAGCCTACAAAATTGGAGTTGTCATTTTTAAAAAGCACATCAGACTGCGGTGGCTCACGGAATCTCAGCACTTTGGGAGGCCAAGGCGGGTGGGTCACCTGAGGGCGGGAGATCGAGATCAGCCTGGCCAACAAGGCAAAACCCCGTCTCTAGAAAAAATACAAAAATTAGCCCAGCTATTTGGGAGGCTGAATCGCTTGAACCTGGGAGGCGGAGGTTGCAGTGTGCTGATATCATACCACTGCACTCCTGCGTGGGATAGAGAGACTGTCTCAGAAAAAAAAAAGCACATCAGTGTAAAATATTAAGATTAAAATGCCTGTTGATCTCTAGTCCACTGGATGCCTTATTCAAGGTACTGTTGTGCTTAAATGATAGAAATGGTATGATATCTATTTGTTTTACCTATTATGTCATATTCCCCATAATTAATACCTTATATTTAACATACTTTAGGAAGGGCATTTATTAACATCATCTCCTTTGATTCTTGAAAAGGACCTTGTAGAAATACTAGTTCCTCTACTTTTTTCAGTAAGTAATACTACAGAAGGGGGTTCAAAATGTTAGGTTTGCC'

In [ ]:

selected_snp = selected[selected['snp_id'] == '2526240078'] 
dna_seq = selected_snp['dna_sequence'].values[0]

In [134]:
print(f"Length normal sequence: {len(normal_slc19a2)} and length mutated sequence: {len(dna_seq)}")

Length normal sequence: 26062 and length mutated sequence: 26061

In [139]:
mutated_location = 0

for i in range(len(normal_slc19a2)):
    if i >= len(dna_seq):
        break
    if normal_slc19a2[i] != dna_seq[i]:
        mutated_location = i
        print(f"""Mutation found at location: {mutated_location}
              Sequence for normal sequence is {normal_slc19a2[i-5:i+5]} and mutated sequence is {dna_seq[i-5:i+5]}
                and exact nucleotide change is {normal_slc19a2[i]} -> {dna_seq[i]}
              """
              )
        # Stop checking after the first mutation
        break

Mutation found at location: 17887
              Sequence for normal sequence is GGCCCTCTCT and mutated sequence is GGCCCCTCTA
                and exact nucleotide change is T -> C

In [140]:
# convert dna to mrna
seq = "GGCCCCTCTA"
mrna = []
for letter in seq:
    if letter == "G":
        mrna.append("C")
    elif letter == "C":
        mrna.append("G")
    elif letter == "T":
        mrna.append("A")
    elif letter == "A":
        mrna.append("U")

print("".join(mrna))

CCGGGGAGAU

In [43]:
slc19a2_wt_dna = merged[merged['clinical_significance'] == "normal"]
normal_slc19a2 = slc19a2_wt_dna['protein_sequence'].values[0]
print(f"Length of normal sequence: {len(normal_slc19a2)}")

Length of normal sequence: 497

In [44]:
with open("normal_slc19a2_protein.txt", "w") as file:
    file.write(normal_slc19a2)